/**
 * OLL case catalogue generated from OLL_algorithms_deduplicated.xlsx.
 *
 * The source workbook contains 2,053 deduplicated solutions across all 57
 * cases. Algorithms stay in their original notation here; generated scrambles
 * are expanded and normalized to outer-layer U/D/R/L/F/B turns.
 */

const RAW_OLL_CASES = [
    [1,"Dot Cases","F R' F' R U2' F R' F' R2' U2' R'",["(R U2 R') (R' F R F') U2 (R' F R F')","R U2 R2 F R F' U2 R' F R F'","y R U' R2 D' r U' r' D R2 U R'","f R U R' U' R f' U' r' U' R U M'","L' U2 L2 F' L' F U2 L F' L' F","R' U' F R' F' R2 U R f' U' f","r' U' R U' R' U2 r U r U2 R' U' R U' r'","F R U R' U' F' S R U R' U' R' F R f'","y R' U R2 D r' U r D' R2 U' R","F R U R' U' S F' R U R' U' R' F R f'","M R U R' U R U' R' U r U2 r' U' M'","r U R' U R' r2 U' R' U R' r2 U2 r'","R U B' R B R2 U' R' F R F'","U' R U' R2 D' r U' r' D R2 U R'","R U R' S R' U' R U R S' U F R' F' R","F R U R' U' F' U2 F U R U' R' F' r U R' U' r' F R F'","r U2 R2 U' R U' r' U2 F R F'","R U R' U R U' R' U R U2 R' S R' U' R U R U R U' R' S'","R U R' d' R' F' R U2 M' U' M F R' F' r U R U' r'","y F U R U' R' F' R U R' U R U' y R U' R' F'","y S U F R2 U' R2 U' R2 U R2 f'","r U R' U R' r2 U' R' U R' r2 U2 r'","y' R U' R2 D' r U' r' D R2 U R'","R U2 R' l' U l F' U2 R' F R F'","y L' U L2 D l' U l D' L2 U' L","U F R' F' R U S' R U' R' y' r U' r' F R' F' r","U R U R' U R' F R F' U2 y' r' U' R U M'","F R' F' R U2 R U' R' y' r' U r U' r' U' r","y F U R' F R F2 U' y' R' F R F'","y F U R' F R F2 U' F' L F L'","R U B' l U l2 x' U' R' F R F'","y F R U R' U' F' r' U r2 U' r2 U' r2 U r'"]],
    [2,"Dot Cases","f U R U' R' f' F U R U' R' F'",["F (R U R' U') F' f (R U R' U') f'","y' R U' R2 D' r U r' D R2 U R'","F R U R' U' S R U R' U' f'","F R U R' U' F' f R U R' U' f'","y r U r' U2 R U2 R' U2 r U' r'","y2 f U R U' R' S' U R U' R' F'","R' U2 r U' r' U2 r U r' U2 R","y r U r' U2 r U2 R' U2 R U' r'","y2 F R' F' R U2 F R' F' R2 U2 R'","y L F L' U2 R U2 R' U2 L F' L'","y R' F' r U2 r' F2 R U2 R' F R","r' D R2 U R' U2 R U' R2 D' r","F R' F' U2 r U R' U R2 U2 r'","F R U r' U' R U R' M' U' F'","y' r' U' R U2 R' U2 r U2 r' U r","y R' F' r U2 L' U2 l U2 R' F R","R' F' U' f U' R U R' S' U R","y r U R' U2 R U2 r' U2 r U' r'","U r U r' U2 r U2 R' U2 R U' r'","y' L' U R L U2 R' U L F' L' F U R' F R F'","y l' U' l U2 L' U2 L U2 R' F R","y R' U R2 D r' U' r D' R2 U' R","y R' F' R U2 r' F2 r U2 R' F R","y2 F R' F' R2 U R' F' U2 F U' R U' R'","y2 R U R' U F' U2 F R U' R2 F R F'","M' U' r' F R U F U' R U R' U' F'","y l' U' l U2 L' U2 L U2 l' U l","y R' F' R U2 L' U2 L U2 R' F R","y2 F' L' U' L U S' L' U' L U f","F R U R' U' F' U2 F U R U' R' F'","y' F R' F' R U2 F R' F' R U2 R' F R U R U' R' F'","y l' U' l U2 l' U2 L U2 L' U l","y' l U L' U2 L U2 l' U2 l U' l'","y2 F U R U' R' F' R' U' R' F R F' U R","y2 f U R U' R' f' F U R U' R' F'","U L F L' U2 R U2 R' U2 r U' r'","R U2 R2 F R F' U2 R' F R F' U2 F R' F' r U R U' r'","y' F R U' R' F R U' R' F' L' U L F' L' U L","y' L' U L2 D l' U' l D' L2 U' L","U' R U' R2 D' r U r' D R2 U R'","r' U' r R' U' R U' R' U R U2 r' U r","U' R2 F R F' U' R U' R2 F R F' U R","U' F R' F' R U' F' U' r U2 R' U r' F2 R","U' R U R' S U' R' U S' U R' U F' U F R","U2 F R' F' R U2 F R' F' R2 U2 R'","U F R' F' R U2 R U' R' F' r' F2 r U F","U R U R' U' R f R f' U R' F' U' r U' r' F2","F R' F' R U R U' f R f' U R' U' R U' R'","R U R' U2 F' U' L' U L U F U' R U2 R'","y' r' U' r U2 R' U2 R U2 r' U r","y' R' F R F' U2 R' F R F2 U2 F","y' R' F R F' U2 R' F R y' R2 U2 R","U2 R U S R' U R U' F R' f' R'","U' F' L' U L F' L' U L F U' R' F R2 U' R'"]],
    [3,"Dot Cases","F U R U' R' F' U f U R U' R' f' y",["y' f (R U R' U') f' (U') F (R U R' U') F'","y' f R U R' U' f' U' F R U R' U' F'","y R' F2 R2 U2 R' F R U2 R2 F2 R","r' R2 U R' U r U2 r' U M'","M R U R' U r U2 r' U M'","f U R U' R' S' R' F' R U R U' R'","y F U R U' R' F' U F R U R' U' F'","F U2 F R' F' R U R U R' U F'","y2 M' U r' U2 r U R' U R2 r'","M U l' U2 l U L' U L M'","y' f R U R' U' f' U f U R U' R' f'","y' x' R U2 R2 F2 R U R' F2 R2 U2 R' x","y2 R' U F' U F U F R' F' R U2 R","f U R U' R' S' R U' R' U' R U R' F'","y F R U R' U' R U R' U' F' U' F R U R' U' F'","L' l U l' U2 l U L' U L M'","y f' L' U' L U f U F R U R' U' F'","R r' U R' F2 R U r' F r2 R'","R f' U' f U R D r' U' r D' R'","y' F R U R' U' F' U f' L' U' L U f","y' F R U R' U' F' U2 R' U' F' U F R","r' R U R' F2 R U L' U L M'","L F' L' F U S' L U L' U' L' S","y' R U R' U' R' F R F' U f' L' U' L U f","y2 M' L U L' U l U2 l' U M","S R U R' U' f' U' F R U R' U' B' R' F R S z'","R U R' S U R U' R' S2 R U' R' S","y F R U' R' U' R U R' U' R' F R F' R U R' F'","U F R U' R' U' R U R' U' R' F R F' R U R' F'","y' F R U R' U' F' R U R' F' U2 F R U' R'","U' F R U R' U' F' R U R' F' U2 F R U' R'","y R' D' r U' r' D R U F R' F' R","y' F' U' L' U L F U' F R U R' U' F'","y2 l' L2 U L' U l U2 l' U M","L' U' L U L F' L' S' L' U' L U f","F R' F' R U' S U' R U R' S' R U R'","y' f R U R' U' f' R' F' U' F U R","y2 L F U F' U' F U F' U' L' y' L F U F' U' L'","y' F' U' L' U L F L F U F' U' L'","U' f R U R' U' f' U' F R U R' U' F'","r' R2 U R' U r U2 r' U r R'","L' l U R' F2 R U L' U L r R'","L' R2 B R' B L U2 L' B M' x'","y' F R' F' R U R U' R' U' R U R' U' R' F R F'","r' R2 U R' U r U2 r' U R' r","y2 R' U' F' U F R F R U R' U' F'","r U R' U R U2 r' U r U R' U' r' R U R U' R'","y L U2 L F' L' F U F U F' U L'","y' S U R U R2 U' R2 U R U S'","y L F2 L2 U2 L F L' U2 L2 F2 L'","y f' L' U' L U f U' F' L' U' L U F"]],
    [4,"Dot Cases","F U R U' R' F' U' f U R U' R' f' y",["y' f (R U R' U') f' (U) F (R U R' U') F'","y' R' F2 R2 U2 R' F' R U2 R2 F2 R","y' f R U R' U' f' U F R U R' U' F'","R' F R F' U' S R' U' R U R S'","y F U R U' R' F' U' F R U R' U' F'","l L2 U' L U' l' U2 l U' M'","y2 M' R' U' R U' r' U2 r U' M","R U R' U' R' F R S R U R' U' f'","y x' R U2 R2 F2 R U' R' F2 R2 U2 R' x","R r2 F' r U' R' F2 R U' M'","R' F' U' F U R f R U R' U' f'","M U' r U2 r' U' R U' R2 r","y' f R U R' U' f' U' f U R U' R' f'","y F U' R U' R' U' R' F R F' U2 F'","y' F R U' R' U R U R' F' f R U R' U' f'","U' f R U R' U' f' U F R U R' U' F'","R r' U' r U2 r' U' M' r' R2 U' R' M'","y F U R U' R' F' U F' L' U' L U F","r' R U' r U2 r' U' R U' R' M'","r' R U' r U2 r' U' R U' R2 r","M r' F' r U' R' F2 R U' M'","y' f R U R' d' l' F R U R' U' F'","F' U2 F' L F L' U' L' U' L U' F","y' R' U2 R' F R F' U' F' U' F U' R","l L' U' L F2 L' U' R U' R' M'","y' S U' R' U' R2 U R2 U' R' U' S'","y' F' U' L' U L F U F R U R' U' F'","y2 R' M' U' R U' r' U2 r U' M","y2 F' L' U' L U F U F R U' R' U' R U R' F'","l' U' L U' L' U2 l U r' U' R U R' r U' R' U R","y F' L F L' U' L' U L U L' U' L U L F' L' F","M U' r U2 r' U' R U' M' R'","f' U' r' F r S r U r' U' r' F r","U' R' F2 R2 U2 R' F' R U2 R2 F2 R","y' F' L' U L U L' U' L U L F' L' F L' U' L F","y2 R' F R F' U' R' D' r U r' D R","y2 F R' F' R U R U' R' U R U R' U' R' F R F'","f R U R' U' f' y R' F R U R' U' F' U R","L' U' L U' L' U2 L S' R U R' S U' M' U R U' r'","y2 L F U F' U' F U F' U' L' F R U R' U' F'","y F' L' U' L U F U' f R U R' U' f'","L' U' L U' L' U2 L R U R' U' M' U R U' r' U2 r U R' U' M U R U' R'","y f' L' U' L U f U F' L' U' L U F","y f' L' U' L U f U' F R U R' U' F'","R' F' R U' S r' F M' F R S'","M L' U' L U' l' U2 l U' M'","y2 r R2 U' R U' r' U2 r U' M","y F U R U' R' F' R' F' U' F U R","l' U' L U' L' U2 l2 U L' U' M' U L U' L'","y2 M' R' U' R U' r' U2 r U' r' R","U' R' U' F' U' F R U' R' F' U' F U' R","y2 r' U' R U' R' U2 r2 U R' U' M U R U' R'","y' f' U' L' U L f L U F U' F' L'","y' L F2 L2 U2 L F' L' U2 L2 F2 L'"]],
    [5,"Square Shapes","r' U' R U' R' U2' r",["r' U2 (R U R' U) r","r' U2 R U R' U r","y2 l' U2 L U L' U l","y2 R' F2 r U r' F R","y2 R' F2 L F L' F R","F R U R' U' F' U' F R U R' U' F'","y2 l' U2 L U r' F R","U2 l' U2 L U L' U l","y2 F U' R2 D R' U R D' R2 U F'","y' F U R U2 R' U' R U R' U R U' R' F'","y R U R2 F R F' U' F' U2 F","y2 R' U' R d' R2 B' R' B R'","y2 R U' R2 U' R U R' U' R' U R2 U' R2 U' R U' R' U' B U B' U2 R' U R","y2 F R' F R F2 r' F2 r","y2 R' F R' F' R2 y U' R U' R'","y' F' r2 F r U' r F"]],
    [6,"Square Shapes","r U R' U R U2' r'",["r U2 (R' U' R U') r'","r U2 R' U' R U' r'","F U' R2 D R' U' R D' R2 U F'","y2 l U2 L' U' L U' l'","y' x' D R2 U' R' U R' D' x","L F2 l' U' l F' L'","y' F R2 B' R' B R' F'","y2 R U R2 F R F2 U F","R U' R' U2 r U' r' U' r U r'","L F2 R' F' R F' L'","y2 R B2 r' U' r B' R'","F R U R' U' F' U' F U R U' R' F'","F R U R' U' F' U f R U R' U' f'","y2 F' L' U' L U F U F' L' U' L U F","F' U' F2 R' F' R U R U2 R'","R U R' U' R' F R F' y S R U R' U' R' F R f'","y' R' F R' F' R2 B U2 B'","y2 R U R' U y' R2 F R F' R","y B r2 B' r' U r' B'","U2 l U2 L' U' L U' l'"]],
    [7,"Lightning Shapes","r U2' R' U' R U' r'",["r (U R' U R) U2 r'","r U R' U R U2 r'","S' R U R' U R U2 R' U S","L' U2 L U2 L F' L' F","y2 l U L' U L U2 l'","F R' F' R U2 R U2 R'","r U r' U R U' R' r U' r'","y2 R' U2 R U2 R f' U' f","L F R' F R F2 L'","r U R' U' M U2 R U2 R'","y x2 F r D' r F r2 F' x2","r' F2 r U2 L F' L' F","R U R' U R U' R' U' M' U R U' r'","y' F R B' R B R2 F'"]],
    [8,"Lightning Shapes","r' U2' R U R' U r y2'",["y2 r' (U' R U' R') U2 r","y2 r' U' R U' R' U2 r","l' U' L U' L' U2 l","R U2 R' U2 R' F R F'","R' F' r U' r' F2 R","S L' U' L U' L' U2 L U' S'","y2 r' U' r U' R' U R r' U r","R' F' r U' L' U2 l","y2 R U' R' L' U2 L R U' R' F2 R' F' R F'","l' U' l U' L' U L l' U l","R' F R U' R' F' R U2 L' U' L","y' R' F R F' U2 F' U2 F","U2 L' B' R B' R' B2 L","y x2 B' r' D r' B' r2 B x2","R' F' R U' L' U L R' F R","U2 r' U' R U' R' U2 r","y' B' R' F R' F' R2 B","R' F' L F' L' F2 R","y2 L' B' L U' R' U R L' B L","F' L F L' U2 L' U2 L"]],
    [9,"Fish Shapes","F U R U' R2' F' R U R U' R' y'",["y (R U R' U') (R' F R) (R U R' U') F'","y R U R' U' R' F R2 U R' U' F'","R U2 R' U' S' R U' R' S","y2 F' U' F r U' r' U r U r'","y' L' U' L U' L F' L' F L' U2 L","M R U2 R' U' R U' R' U' M'","y2 R' U' R U' R' U R' F R F' U R","y R' U' R y r U' r' U r U r'","y R' U' R y' x' R U' R' F R U R' x","y' r' F' r U' r U' r' F r' F2 r","r' R2 U2 R' U' R U' R' U' M'","S' R U2 R' U' R U' R' U2 S","U R' U' R U' l U' R' U x R' U2 R","y R U R' U R U2 R' f R U R' U' R U R' U' f'","y R' U' R y' l U' l' U R B R'","y2 S U2 R U2 R' U' R U' R' S'","y l' U' l U l F' l' F R' F R F' R U R'","y' L' U' L y' L F' L' U r U r'","y R' F R' F' R U R U' R2 F R F' R","y2 L' U' L U' L F' L' F L' U L U L F' L' F","U R' U' R F R' F' U F R F'","y' L' U' L y l U' l' U l U l'","y R U R' F' R U2 R' U2 R' F R U' R' F R F'","y' L' U' L y' L F' L' U L F L'","r' R2 U2 R' U' R U' R' U' R' r","y2 F' U' L' U L y' U' R U' R' U2 R","U R U R' U' R' F R2 U R' U' F'","y R' U' R F R' F' U F R F'","y R' U' R y' R B' R' U R B R'"]],
    [10,"Fish Shapes","R U2' R' F R' F' R U' R U' R'",["(R U R' U) (R' F R F') (R U2 R')","R U R' U R' F R F' R U2 R'","y F U F' R' F R U' R' F' R","y M' R' U2 R U R' U R U M","y2 L' U' L U L F' L2 U' L U F","y R' U2 R U S' R' U R S","y r R2 U2 R U R' U R U R r'","R U R' y R' F R U' R' F' R","R U R' U l' U R U' l U2 R'","y S' R' U2 R U R' U R U2 S","y' r' F2 r U S r' F r S'","U R U R2 F' U' F R2 U' R2 U2 R","y2 L U L' y' l' U l U' l' U' l","y F U R U' R' F' U' R U R' U R U2 R'","y2 r' F' r U r U' r2 F' r U F","R' U' R2 f R f' U' R' U R' U R","R' U' R2 f l U' R' B' l U' R U z'","y M' R' U2 R U R' U R U r' R","y R' U2 r' R2 U R' U R U' M'","R U R' y' r' U r U' r' U' r","y R U R' U R U' R' U' B' R' F R F' B","y S' U2 L' U2 L U L' U L S","y R U R2 F' U' F R2 U' R2 U2 R","y F R U R' U' F' U R' U' R' F R F' U R","y2 r U r' U' r' F r F' L F' L' F L' U' L","R U R' y R' F R U' l' U' l","y U' R U R' U R' F R F' R U2 R'","y' M L' U2 L U L' U L U M'","U r R2 U2 R U R' U R U R r'","U r R2 U2 R U R' U R U M","y' S r' F2 r U r' F r U2 S'","y F U F' l' U l U' l' U' l","U2 L U L' F' L F U' F' L' F","y' L' U2 L U S L' U L S'","y' l L2 U2 L U L' U L U M'","y' R r' L' U2 L U L' U L U M'","y2 L' U' L F L' U2 L U2 L F' L' U L F' L' F","y' f R U R' U' f' U R U R' U R U2 R'","y' R U R' U F' U F U' R U2 R'","y F U R U' R' y U L' U L U2 L'","R U R' U x R' U R U' R x' U2 R'","y2 r U R' U R U' R' U' M U R U' R'","y' f R f' r' U r U' r' U' r","y r R2 U2 R U R' U R U M","y R U R' U R' F R F' R U' R' U' R' F R F'","y2 L U L' F' L F U' F' L' F"]],
    [11,"Lightning Shapes","M U' R U2' R' U' R U' R2' r",["M (R U R' U R U2 R') U M'","r' R2 U R' U R U2 R' U M'","y2 r U R' U R' F R F' R U2 r'","S R U R' U R U2 R' U2 S'","M R U R' U R U2 R' U M'","y2 S' U2 R U R' U R U2 R' S","y F' L' U' L U F U F R U R' U' F'","y S' U L U L' U L U2 L' S","f U R U' R2 F' R U R U' R' S'","y' S U R U R' U R U2 R' S'","y2 M' L U L' U L U2 L' U M","r' R2 U R' U R U2 R' U R' r","y' R' F' U' F2 R' F' R2 U' R' U2 R","y' U' r U R' U R' F R F' R U2 r'","R2 r' U R' U R U2 R' U M'","U2 R U R' U' R' F R F' L' U' L U L F' L' F","R U R' U R U' R' S' R U' R' S","R U R' U R U R' S' R U R' S","U2 l' L2 U L' U L U2 L' U M","y2 f R U R' U' R U R' U' f' U' R U R' U' R' F R F'","y2 R' u' R U' R U R' u R U' R U' R'","M2 r U R' U R U2 R' U M'","y F' L' U' L U F U' F' L' U' L U F","U2 r U R' U R' F R F' R U2 r'","L' l R U R' U R U2 R' U M'","y2 L F R' F R' D R D' R F2 L'","y' l' U' L U' L' U2 B' l U' R' U2 R","y' F' U' L' U2 L U' L' U' L U' L' U L F","y' l' U' L U' L' U2 l U2 L' U' L U' L' U2 L","y2 R' L2 F L' F L F2 L' F L' R","y F R U R' U' F' U r U R' U R U2 r'","y' l' U' L U' L' U2 x' U' R U' R' U2 R"]],
    [12,"Lightning Shapes","F U R U' R' F' U' F U R U' R' F'",["y' M' (R' U' R U' R' U2 R) U' M","y' M' R' U' R U' R' U2 R U' M","F R U R' U' F' U F R U R' U' F'","y' S R' U' R U' R' U2 R U2 S'","y M L' U' L U' L' U2 L U' M'","y' r R2 U' R U' R' U2 R U' R r'","y l L2 U' L U' L' U2 L U' M'","y' l' U' L U' L F' L' F L' U2 l","y' r R2 U' R U' R' U2 R U' r' R","S U' R' U' R U' R' U2 R S'","y' M' R' U' R U' R' U2 R U' R r'","y S' L' U' L U' L' U2 L U2 S","y2 F U R U2 R' U R U R' U R U' R' F'","y' S U2 L' U' L U' L' U2 L S'","y S' U2 R' U' R U' R' U2 R S","y2 r U R' U R U2 r' U2 R U R' U R U2 R'","y2 S' U' L' U' L U' L' U2 L S","y S' r' F' r U' r' F2 r U2 S","y r' R U2 R' U' R U' R' U2 R U M'","y R r2 F' r U' r' F2 r U' M'","y R u R' U R' U' R u' R' U R' U R","y' M' R' U' R U' R' U2 R U' r' R","y' S U2 r' F' r U' r' F2 r S'","U' l' U' L U' L F' L' F L' U2 l","y' R2 r U' R U' R' U2 R U' R r'","y' R2 r U' R U' R' U2 R U' M","y2 r U R' U R U2 B r' U L U2 L'","y' r R2 U' R U' R' U2 R U' M","y' L R2 F' R F' R' F2 R F' L' R","y2 r U R' U R U2 x' U L' U L U2 L'","y R' U2 R2 U R' U' R' U2 F R2 U R' U' F'","y' R' U' R U' R' U R S' R' U R S","S F' U' F U' F' U2 F U' S'","y2 U M' R' U' R U' R' U2 R U' M","U l L2 U' L U' L' U2 L U' M'","U' M' R' U' R U' R' U2 R U' M","y3 R2 r U' R U' R' U2 R U' R r'","y' R' F' r U' r U' r' F r' F2 R","y' R U R2 D' R U' R' D R2 U' R2 F R F'","y2 S' U' r' F' r U' r' F2 r S","y' R' F' r U' L F' L' F r' F2 R","y r' R U2 R' U' R U' R' U2 R U R' r","U' r R2 U' R U' R' U2 R U' R r'","U l L2 U' L U' L' U2 L U' L l'","y f' U' L' U L2 F L' U' L' U L S","y f' U' r' F r2 U r' U' L' U L S","R U R' U' R' F R F' U R U R' U' R' F R F'","y' R' M' U' R U' R' U2 R U' R r'","y' R B U' B' R2 D' r U r' D R","y U2 r R2 U' R U' R' U2 R U' M","y' R U R' U' R' F R2 U' R' U R U2 R' U' F'"]],
    [13,"Knight Move Shapes","F' U' F r U' r' U r U r'",["(r U' r') U' (r U r') (F' U F)","F U R U2 R' U' R U R' F'","F U R U' R2 F' R U R U' R'","r U' r' U' r U r' F' U F","y2 f R U R2 U' R' U R U' f'","r U' r' U' r U r' y L' U L","r U' r' U' r U r' y' R' U R","L F' L' U' L F L' F' U F","y2 R B' R' U' R B R' f' L f","y2 F R U R2 U' R F' R' U R","F U R U2 R' F R' F' R U F'","y2 F R U R' U' R U' R' U' R U2 R' U' F'","l' U' L U l F' L2 U' L U F","L' U' L U R U R' U' L F' L' F R U R' U R U' R'","y2 R' U' R U' r U R2 U R2 U2 r'","L F' L' U' L F L' y' R' U R","R U R' U' R' F R F' R U R' U R U2 R'","S' L' U' L U L F' L2 U' L U f","y' R U R' S' R U' R' S R' U2 R U R' U R","R U R' U' M' U R U' M U R' U R U2 R'","R U' L' U R' U' L R U R' S' R U' R' S","y2 x' l F' l' F' l F l' U' F U","y2 l U' l' U' l U l' f' L f","y2 l U' l' U' l U l' B' U B","y2 R B' R' U' R B R' B' U B","S R U R' U R U2 R' U2 S' R U R' U' M' U R U' r'","y x' U r' F' D' F r U' r' D r x","y' x' D R' D' F' D R D' R' F R x","y2 l U' l' U' l U l' y' L' U L","r U' r' U' r U r' y z U' R U","y' x U R' U' B' U R U' R' B R"]],
    [14,"Knight Move Shapes","F U F' R' F R U' R' F' R",["R' F (R U R') F' R (F U' F')","R' F R U R' F' R F U' F'","r U R' U' r' F R2 U R' U' F'","l' U l U l' U' l F U' F'","F' U' L' U L2 F L' U' L' U L","y2 R U R' U' R' F R F' R U2 R' U' R U' R'","y2 r' U r U r' U' r y R U' R'","y2 r' U r U r' U' r f R' f'","S R U R' U' R' F R2 U R' U' f'","l' U l U l' U' l y' R U' R'","F' U' L' U2 L U L' U' L F","F' U' r' F2 r U' F R U' R'","F' U' r' F r2 U r' U' r' F r","R' F R U R' F' R y' R U' R'","y2 F' L' U' L U L' U L U L' U2 L U F","R' F R U l' U' l F U' F'","R U R' U r' U' R2 U' R2 U2 r","F U R U' R2 F' R U2 R U' R' U R U2 R'","F' U' L' U2 L F U' R' F R F'","r' F R F' M' S' R U R' S","y2 F U R U' R' F' R U R' U R U' R' U' R' F R F'","r' F' r U' r' F2 r2 U R' U' r' R U R U' R'","L' U2 R U R' U2 L U R' F R F'","y2 r' U r U r' U' r B U' B'","y2 r' U r U L' B' L B U' B'","S' L' U' L U' L' U2 L U2 S R U R' U' M' U R U' r'","y R U R' U R U' R' U R' F R F' R U2 R'","y x' D' r F U F' r' D r U' r' x","y2 f' L' U' L2 U L' f L U' L'","L' U' L U L F' L' F L' U' L U' L' U2 L","F R U' R' U R2 D R' U R D' R2 F'","F R2 U D R2 D' R' D R' U' D' R2 F'","y' x' U' R U F U' R' U R F' R'","r' F R f' r U r' S M'"]],
    [15,"Knight Move Shapes","r' U' r U' R' U R r' U r",["(r' U' r) (R' U' R U) (r' U r)","r' U' r R' U' R U r' U r","y2 l' U' l L' U' L U l' U l","r' U' M' U' R U r' U r","y2 R' F' R L' U' L U R' F R","y2 R' F' R r' F' r U R' F R","y' R' U2 R U R' F U R U' R' F' R","f U f' R' f R U' R' f' R","y2 F R U R' U' F' R' U2 R U R' U R","y R U R' U2 S U' R U R' S' R U R'","y2 R' F' M F' r U R' F R","y2 F U R U' R' F' R' U' F' U F R","y2 L F' L' F L' U L U' L' U' L U' F U F'","y2 l' U' M U' L U l' U l","y2 l' U' M U' L U R' F R","F U R U' R D R' U' R D' R2 U' R U R' F'","y2 R U R' U' R' F R F' R U2 R' U' R U R' U' R U' R'","l' U l U l' U' l y' R U R' U' R U' R'","L F' L' U' L U F L' U L U2 L'","y2 F R U R' U' F' U R U R' U R U2 R'","y2 U2 y2 U2 y2 U2 r' U' r R' U' R U r' U r","y2 U2 y2 U2 r' U' r R' U' R U r' U r","y2 U2 r' U' r R' U' R U r' U r","U2 F R U R' U' F' U R U R' U R U2 R'","U2 R U2 R' U' R U R' U' R U R' U2 R' F R F'","y2 R U R' U' R' F R2 U R' U' R U R' U' R U R' U' F'","U2 L F' L' F L' U L U' L' U' L U' F U F'","F' L' U' L U F2 U y' R' U R U2 R'","U2 l' U' R r' U' L U R' F R","U2 l' U' l L' U' L U l' U l","y2 R' F' L' R U' L U R' F R","y2 r' U r U r' U' r y R U R' U' R U' R'","y z' B' U' S U' F U B' R B","L' B' L R' U' R U L' B L","L' B' L R' U' R U r' U r"]],
    [16,"Knight Move Shapes","r U r' U R U' R' r U' r'",["(r U r') (R U R' U') (r U' r')","r U r' R U R' U' r U' r'","r U M U R' U' r U' r'","y2 R' F R U R' U' F' R U' R' U2 R","y2 l U l' L U L' U' l U' l'","R U' R' S R U' R' U S' U2 R U' R'","L F L' R U R' U' L F' L'","y S' L' U' L U L F' L' f l' U' L U' L' U2 l","R' F R F' R U' R' U R U R' U F' U' F","y2 l U M' U L' U' l U' l'","R U R' U' R' F R2 U R' U' R' F' R U R U' R'","R f R' F' R U R U' R' S' R'","y2 F R U R' U' F' R U2 R' U' R U' R'","f R U R' U' R U R' U' f' U' R U R' U R U2 R'","y2 R U R' U' R' F R F' R U R' U R U' R' U R U2 R'","y2 r U' r' U' r U r' y L' U' L U L' U L","R U R' S R U R' U' S' R U' R'","F' L' U' L U F y' L' U' L U' L' U2 L","y' L U2 L' U' L F' U' L' U L F L'","L F L' R U R' U' r U' r'","y2 U2 r U r' R U R' U' r U' r'","y' R' F' R f z' R' U' F U R f' z","y x r' B' r U r' U' B U r U' x'","y2 R B R' r B r' U' R B' R'","y' z' F U S U B' U' F R' F'","y2 R B R' L U L' U' R B' R'"]],
    [17,"Dot Cases","F R' F' R U2' F R' F' R U' R U' R'",["(R U R' U) (R' F R F') U2 (R' F R F')","R U R' U R' F R F' U2 R' F R F'","y2 F R' F' R U S' R U' R' S","y2 F R' F' R2 r' U R U' R' U' M'","y' F' r U r' U' S r' F r S'","y' f R U R' U' f' U R U R' U' R' F R F'","y2 r U' r' F U2 F U' R U' R' F'","f R U R' U' f' U' R U R' U' R' F R F'","l U' l' f R2 B R' U R' U' f'","F' r U r' U2 r' F U' F U r","U2 F R' F' R U S' R U' R' S","R B' R' f R2 B R' U R' U' f'","y2 F R U' R' U' R U R' F' U R U R' U' M' U R U' r'","y F U R U' R' U' R' F R F' R U R' F'","y F R' F' R U2 R U' B U' B' R'","y2 F R' F' R U R U' R' U R U R' U' M' U R U' r'","y2 F U R U' R' F' U R U R' U' R' F R F'","y' R' U' F' U F R2 U R' U' R' F R F'","y L' U' L U' L F' L' F U2 L F' L' F","y F U R U' R' F' U' R U R' U' R' F R F'","y2 F R' F' R M U R U' R' U' M'","U F U R U' R' U' R' F R F' R U R' F'","y x' R U' R' U y' R S U R' U' S' z'","y R' F' U2 F2 U R U' R' F' U2 R","y2 F U R' U' F' U F R2 U R' U' F'","y2 R' U' F U R U' R' F2 U' F U R","r U' r U' r2 U r2 U r' R' U2 R U r'","y' r' U r' U r2 U' r2 U' r R U2 R' U' r","y' F R U2 R2 U' F' U F R U2 F'","R U R' U x R' U R U' x' U2 x' z' U' R U R'","B L' B' L2 l' U L U' L' U' M","F' U' L' U L U L F' L' F L' U' L F","U2 F R' F' R2 r' U R U' R' U' M'","y2 r U' z U' R x' U2 R U' y R U' R' F'","y2 r U R' U R U2 r' U2 r U2 R' U' R U' r'","U2 r U' r' F U2 F U' R U' R' F'","y' F' r U r' U' S L' U L S'","y2 R U2 r' U' R U M' R' F2 r U r' F","R' F R U' M' U2 r' U' F' U R"]],
    [18,"Dot Cases","r' U2' R U R' U r2' U2' R' U' R U' r'",["y (R U2 R') (R' F R F') U2 M' (U R U' r')","y R U2 R2 F R F' U2 M' U R U' r'","r U R' U R U2 r2 U' R U' R' U2 r","y F S' R U' R' S R U2 R' U' F'","R D r' U' r D' R' U' R2 F R F' R","y' r' U' R U M' U' R2 F R F' U R","F R' F' R U R U' R' U F R U R' U' F'","F R' F' R U2 F R' F' R U' R U' R'","y2 R U2 R' F' U2 F R U' R2 F R F'","y2 r' U' R U' R' U2 r2 U R' U R U2 r'","y R' F' U' F U' R U2 R f' U' f","y2 R U R2 F' U' F U R U2 R' F R F'","y2 R U R' U R' F R F' U2 M' U R U' r'","y2 F R U R' U y' R' U2 R' F R F'","y R f R f' U R' U2 R' F R F'","y' F R U' R' U' R U R' F' U' F R U R' U' F'","y R U2 R' F' L' U2 L F R U2 R'","y2 R2 D' r U r' D R2 r' U r U' r' U' r","l' U' L U' L' U2 l2 U L' U L U2 l'","y2 F R U R' U F' U2 F' r U r'","y F R U R' U' F' U2 r U R' U' r' R U R U' R'","y F R U R' U' F' U M' U' M U2 M' U' M","y' F R U R' U' F' y2 F R U R' U' R U R' U' F'","y R U R' U' R' F R F' y2 F R' F' R U R U' R'","U R U2 R2 F R F' U2 M' U R U' r'","y' F U R U' R' S F' R' F R S' R' F' R","y' F U R U2 R' S' R U R' S F'","y2 F R U R' Dw R' U2 R' F R F'","y2 F R U R' U F' U2 y' R' F R F'","y2 F R U R' U F' U2 F' L F L'","f U R U' R' f' U l' U' L U' L' U2 l","y R U2 R2 F R F' U2 r R' U R U' r'","y R D r' U r D' R' U' r' U' R U M'","y R U R' U' M' U R U' r' f R U R' U' f'","y R U R' U' R' F R F' U2 F R' F' R U R U' R'","y f R U R' U' f' U R U R' U' L R' F R F' L'","y S' R U R' S R U' R' F R U R' U' F'","U2 R U R' U' L' U' L U R' F R F' L' U' L2 F' L' F","y f R U R' U' f' U' R U R' U' M' U R U' r'","y' F U R U' R' U R U' R' F' U2 F U R U' R' F'","y R U2 R2 F R F' U' S R U' R' U S'","y2 F R U R' U' F' U r' U' R U' R' U2 r","f R U R' U' f' U' r U' r' U' r U r' F' U F","r U R' U R U2 r' U2 R U2 R' U2 R' F R F'","y2 l U L' U L U2 l2 U' L U' L' U2 l","y R U R' U L' U' L U L F' L' F U R' F R F'","y' F U R U' R' F' U R U R' U' M' U R U' r'","y2 F R U R' d R' U2 R' F R F'","y' F R U R' U' F' U2 F R U R' U' R U R' U' F'","r U R' U R U2 r' U2 l' U' L U' L' U2 l","y2 F' U' F U2 L F' L' F U F R U' R2 F' R","y R' F R2 U R' F' U' F' L F L' U2 F' U F","y2 F R U R' y' U R' U2 R' F R F'","y R' U' F R' F' R2 U M U' R' U r","y' R' F R F' U2 R' F R F' U F' U F","y2 S U R' U' R S' R2 F R F' U R","y' F D R D' S D R' U D' R U' R' Fw'","y r U' r' F U F U' R U R' U' F'","R' U' F' U F R2 U R' U' M' U R U' r'"]],
    [19,"Dot Cases","F R' F' R M U R U' R' U' M'",["M U (R U R' U') M' (R' F R F')","y S' R U R' S U' R' F R F'","M U R U R' U' M' R' F R F'","R' U2 F R U R' U' F2 U2 F R","r' R U R U R' U' r R2 F R F'","r' R U R U R' U' M' R' F R F'","y2 r U2 R' U' R U' r2 U2 R U R' U r","y2 F R' F' R U R U' R' U' F R U R' U' F'","y' S r' F' r S' U r U' r' F","M U R U R' U' r R2 F R F'","r' U2 R U R' U r2 U2 R' U' R U' r'","y F S' R U' R' S U R U R' F'","y R U R' U' R' F R F' U2 r U R' U' r' R U R U' R'","y2 F U R U' R2 F' U' F U R U' F'","y' F U2 R' F' U' F U R2 U2 R' F'","R r' U R U R' U' M' R' F R F'","y S R U R' U' R' F R f' U R U R' U' M' U R U' r'","y2 F R' F' R U R U' R2 F' U' F U R","M U' L' U' L U M' L F' L' F","F' L F L2 U L F R' F' R U' L' U L U R U' R'","y' F R U' R' U' F R U R' U' F' R U R' F'","U R U R' F' U' R U R' U' R' F R U' M' U R U' r'","r' R U R U R' U' R2 r F R F'","U2 F R' F' R U R U' R' U' F R U R' U' F'","y2 l' U2 L U L' U l2 U2 L' U' L U' l'"]],
    [20,"Dot Cases","r U R' U' M2' U R U' R' U' M'",["(r U R' U') M2 (U R U' R') U' M'","r U R' U' M2 U R U' R' U' M'","M' U2 M U2 M' U M U2 M' U2 M","S' R U R' S U' M' U R U' r'","S R' U' R U R U R U' R' S'","M U R U R' U' M2 U R U' r'","R U R' U' R' F R F' R U2 R2 F R F' R U2 R'","M' U' M' U' M' U' M' U M' U' M' U' M' U' M'","M' U2 M U2 M' U' M U2 M' U2 M","r' R U R U R' U' R2 r2 U R U' r'","M U M U M U M2 U M U M U M U M U M U M U M2 U M U M U M","S U' R U R' S2 R U' R' S","R2 S' R2 U' S2 U' R2 S' R2","S' R U R' S2 R U' R' U S'","M' U' R' U' R U M2 U' R' U r","M U M' U2 M U M' U M U M' U2 M U M'","f R U R' U' f' R' F' U' F R U' R' U2 R","r U R' U' M U R U' R' y R U R' U' M' U R U' r'","F U R U' R' F' U2 R' U' R' F R F' U R","M U M F R' F' M2 F R F'","f R U R' U' f' R' U' R' F R F' U R","r U R' U' r2 R2 U R U' R' U' M'","M U' L' U' L U M2 U' L' U l","r' R U R U R' U' L2 l2 U R U' r'","r U R' U' M U S' R U' R' S","M' U M' U M' U M' U' M' U M' U M' U M'","R U R' U' M' U R U' r' U2 r U R' U' M U R U' R'","F R' F R2 U R' U' F2 U' L F' L' F","F R' F' R M2 R' F R F' M' U' M'","M' U2 M U2 M' U' M U2 M' U2 M","M' U M U2 M' U M U M' U M U2 M' U M","R U' R2 F2 U' R F' R' U F2 R2 U R'","y F' L F M2 F' L' F M' U M'","S R U R' U' R' U' R' U R S'","r' R U R U R' U' M2 U R U' r'","M' U' M U r U R' U' M U R U' R' U2 M' U2 M","r U R' U' r' R U S' R U' R' S","R U2 R' U' R U' R r' U R' U r U2 r' U M'","U M' U M' U M' U M' U' M' U M' U M' U M'","M' U' M U2 M' U' M U' M' U' M U2 M' U' M","R' F R S2 R' F' R S' U S'","r U R' U' r2 R2 U R U' R' U' R' r","M U M U M U M U M' U M' U M' U M'","r' R U R U R' U' R' M' r U R U' r'","r U R' U' r2 R2 U R U' R' U' r R'","M' U2 M' U2 M' U M U2 M U2 M","R U' R2 F2 U' R F R' U F2 R2 U R'","r U R' U' r R' M' U R U' R' U' M'","r U R' U' R' M' r U R U' R' U' M'","l' U' L U M2 U' L' U L U M'","M' U' M' U' M' U' M' U' M U' M U' M U' M","M U R U R' U' L2 l2 U R U' r'","L R' F2 L' R U2 L R' F L' R U2 L R' F2 L' R","M' U' M' U' M' U' M' U M' U' M' U' M' U' M'","r' R U R U R' U' r2 R2 U R U' r'","M U2 M' U2 M U M' U2 M U2 M'"]],
    [21,"OCLL","R U R' U R U' R' U R U2' R' y'",["(R U R' U) (R U' R' U) (R U2 R')","R U R' U R U' R' U R U2 R'","y R U2 R' U' R U R' U' R U' R'","y F R U R' U' R U R' U' R U R' U' F'","R' U' R U' R' U R U' R' U2 R","y F U R U' R' U R U' R' U R U' R' F'","y R' U2 R U R' U' R U R' U R","y' F R U R' U' R U R' U' R U R' U' F'","y F R U R' U' R U R' U' R U R' U' F' y'","L U L' U L U' L' U L U2 L'","R U R' U R U r' F R' F' r","U y2 R2 U' L2 F2 L' F2 L D' F2 D' L D2 L' F2 L' F2 L D' F2 D' L D2 L U R2 y2","y R U2 D2 R' U' R U' R' U2 R D2 R' U y R U2 D2 R' U' R U' R' U2 R D2 R'","U' F R U R' U' R U R' U' R U R' U' F'","y f U R U' R' U R U' R' U R U' R' f'","y f R U R' U' R U R' U' R U R' U' f'","U F R U R' U' R U R' U' R U R' U' F'","y R' F2 R2 U2 R' F2 R U2 R2 F2 R","y' R U2 R' U' R U R' U' R U' R'","F R U' R' U R U2 R' U' R U R' U' F'","R2 U' L2 F2 L' F2 L D' F2 D' L D2 L U R2","U F R U R' U' R U R' U' R U R' U' F'","y R' U' R U' R' U2 R F' r U R' U' r' F R","L' U' L U' L' U L U' L' U2 L","R U R' U R U2 U R' U R U2 R'","L' U R U' L U R' U' R U2 R' U' R U' R'","R B U B' U' B U B' U' B U B' U' R'","y L' U2 L U L' U' L U L' U L","U R U2 R' U' R U R' U' R U' R'","U R U2 R' U' R U R' U2 R' F R2 U' R' U' R U R' F'","U' f R U R' U' R U R' U' R U R' U' f'","R U R' U R U L' U R' U' L","f R U R' U' R F' R U R' U' R' S'","R' F' R U2 R U2 R' F U' R U' R'"]],
    [22,"OCLL","R' U2' R2' U R2' U R2' U2' R'",["R U2 (R2' U') (R2 U') (R2' U') U' R","R U2 R2 U' R2 U' R2 U2 R","R' U2 R2 U R2 U R2 U2 R'","f R U R' U' S' R U R' U' F'","f R U R' U' f' F R U R' U' F'","y2 L' U2 L2 U L2 U L2 U2 L'","R U R' U' R' U2 R U R' U R2 U2 R'","y2 L U2 L2 U' L2 U' L2 U2 L","y' R U R' U F' R U2 R' U2 R' F R","y' R' U' R U' R' U2 R2 U2 R' U' R U' R'","R U' L' U R' U' L U' R U R' U R U2 R'","R' U' R U' R' U2 R U R' U' R U' R' U2 R","F S R U R' U' S' R U R' U' F'","y2 F R U R' U' R U R' U' S R U R' U' R U R' U' f'","R U' z U' R D' R U R U' R U z'","F R U R' U' R U R' U' F' R U R' U' M' U R U' r'","y R U R' U R U2 R2 U2 R U R' U R","y F R2 U' R2 U R2 U S R2 f'","U' r U R' U R' F R F' R U' R' U R U2 r'","R U' L' U R' U L U L' U L","y F U R U' R' U R U2 R' U' R U R' F'","y F U R U' R' U R U' R2 F' R U R U' R'","R U D' R U R' D R2 U' R' U' R2 U2 R","y' R' U' R U' R' U2 R U' R' U' R U' R' U2 R","R U2 R' U' R U' R' U' R U2 R' U' R U' R'","R' F' U' F U' R U S' R' U R S","y2 F U R U' R' F' U2 F R U R' U' F'","R U R' U' R' F R2 U R' U' R U R' U' F'","R2 D' R U R' D R U R U' R' U R U R' U R","R U R' U R U2 R' U' R U R' U R U2 R'","y R U R' U' L' U' L U' L' U L U' R U' R' U L' U L","U' F U R U2 R' U R U R' F' R U2 R' U' R U' R'","R' U' F' R U R' U' R' F R2 U2 R' U2 R","y x' R U R' D R U' R' D' R U' R' D R U R' D' x","R' U2 R U R' U R U R' U2 R U R' U R","y2 F U R U' R' S U R U' R' f'","y2 L U' R' U L' U R U R' U R","y2 L' U R U' L U' R' U' R U' R'","y' R U2 R' U R' D' R U2 R' D R2 U' R'","y2 r' F R F' r U' R' U' R U' R'"]],
    [23,"OCLL","R U2' R D R' U2' R D' R2'",["R2 D (R' U2 R) D' (R' U2 R')","R2 D R' U2 R D' R' U2 R'","y2 R2 D' R U2 R' D R U2 R","R U R' U R U2 R2 U' R U' R' U2 R","y R U R' U' R U' R' U2 R U' R' U2 R U R'","y' R U2 R' U' R U' R' L' U2 L U L' U L","R U R' U R U2 R' y R U2 R' U' R U' R'","R U' L U' R' U L' U2 R U' R'","R2 D R' U2 R D' R' U2 D D' R'","L2 D' L U2 L' D L U2 L","y2 R' U2 R F U' R' U' R U F'","y2 R' U2 R U2 R' F' R U R' U' R' F R2","U F R U R' U' F' r U R' U' r' R U R U' R'","y2 F R U' R' U R U R' U R U' R' F'","U2 R2 D' R U2 R' D R U2 R","y F U2 F' R' U F U F' U' R","U2 R2 D' R U R' D R U R U' R' U' R","R U R' U R U2 R' U R U2 R' U' R U' R'","U r U R' U' r' F R F' R' F' L' F R F' L F","R' D R D' R' D R U' R' D' R D R' D' R","y2 R' F R2 U' r' F R' F' r U R' F' R","y2 L2 D L' U2 L D' L' U2 L'","y2 R' U' R U' R' U2 R2 U R' U R U2 R'","R U2 R' U L' U2 R U' R' U2 L","x2 D' R U R' U' R U R' U' D' U R U' R' U R U' R' x2","y2 R U' R' U' R U R D R' U R D' R2","y' R U R2 F' r U R2 U' r' F U' R'","f R U R' U' R f' U' r' U' R U M' f R U R' U' R f' U' r' U' R U M'","y' U R' U2 L F2 L' F2 R2 U2 R U2 R' U2 F2 R2 F2 y","y' R' D' R D R' D' R D U R' D' R D R' D' R D R' D' R D R' D' R D","y' R U R' U R U' R' U' R' F R U R U' R' F'","y2 l2 U' R D2 R' U R D2 R x2","R U R' U R U2 R' U R U2 R' U' R U' R'","R' D R D' R' D R U' R' D' R D R' D' R","U R' U' R U2 R D R' U2 R D' R2 U R","U R U R' U2 R' D' R U2 R' D R2 U' R'","y R U R' U' R U R' U' L' U R U' R' U R U' R' L","U2 R' U' R U' R' U2 R2 U R' U R U2 R'","R' F2 R U2 R U2 R' F2 R U2 R'","y2 R' F R' F R2 U' R' U' R U R' F' R U R' U' F' R","x' R U R' U' R U R' D R U' R' U R U' R' D' x","y' R2 D' R U' R' D R2 U' R' U2 R","y2 R' F R U' R' U' R U R' F' R U R' U' R' F R F' R","R U' L' U R' U' L U2 L' U R U' L U R'","R U2 x R U2 R U2 R' U2 L U2 r' U2 R U2 R' U2 R'","y2 z U R2 U' F' R U R U' R' F z'","y' R U2 R' U' R U' R' U' R U R' U R U2 R'","R U2 x R U2 R U2 r' U2 L U2 R' U2 R U2 R' U2 R'","U2 R' F R U' R' U' R U R' F' R U R' U' R' F R F' R","R' U2 L F2 L' F2 R2 U2 R U2 R' U2 F2 R2 F2","U' R U2 R' U' R U' R' U' R U R' U R U2 R'","y2 R U R' U' R' F2 R2 U' R' U' R U R' F2","x2 R2 U R' D2 R U' R' D2 R' x2","R U R' U R U2 R' U2 L' U' L U' L' U2 L","U' R' U' R U' R' U2 R U' R' U2 R' D' R U2 R' D R2","R2 D R' U2 R D' R' U R U R U R U' R' U' R2","U' R U2 R' U' R U' R' U2 R' U2 R U R' U R","U' R' U R' D' U' R U' R' U2 R U' R' D R U' R","R U R' U R U2 R' y R U2 R' U' R U' R'","y2 r U' r2 F R F' r U R' U' r U r'","y2 x' R U' R' D R U2 R' D' R U' R'","y F2 R U' R' U' R U R' F' R U R' U' R' F R F2","R2 B2 U2 L U2 R' U2 R U2 F2 R F2 L' B2 R2","y2 R' U2 R F' R' F U2 F' R F","x R2 F R' B2 R F' R' B2 R'","L' U' L U' L' U2 L2 U L' U L U2 L'","y F R U R' U' R U R' U' F2 L' U' L U F"]],
    [24,"OCLL","F R' F' r U R U' r'",["(r U R' U') (r' F R F')","r U R' U' r' F R F'","y2 R' F' r U R U' r' F","y' x' R U R' D R U' R' D' x","y R U R D R' U' R D' R2","y' R' U' R' D' R U R' D R2","L F R' F' L' F R F'","x L U R' U' L' U R U'","y R' F' R U R' U' R' F R U R","y2 l' U' L U R U' r' F","y' l U R' D R U' R' D' x","r U R' U' L' U R U'","y' R' U2 R U R' U R2 U2 R' U' R U' R'","x U R U' L U R' U' L' x'","U' x' R U R' D R U' R' D' x","F R F' r U R' U' r'","U R' F' R U R' U' R' F R U R","y2 l' U' L U l F' L' F","U' F R' D' R U R' D R U' F'","r U' r' U2 r U r' y' R' F' U2 F R","r U' r' U2 r U r' y L' B' U2 B L","y2 R' F' L F R F' L' F","R U R' U' L' U R U' M' x'","y l' U' R D' R' U R D","y R U' R2 D' r U' r' D R2 U R' y R U' R2 D' r U' r' D R2 U R'","R U R' U' L' U R U' M'","U2 x R' U' L U R U' L' U x'","y' R2 U2 R2 U' R2 U' R2 U R U' R' U R U' R' U R U' R'","y R' U R2 U R' U R' U' R U' R' U' R U R U' R'","y l' U' R D' R' U R D x","r' U' R U L U' R' U x","y x D L U' L' D' L U L'","R U R' U R U2 R' L' U' L U' L' U2 L","U2 R' F' r U R U' r' F","U R' U2 R U R2 F R U R U' R' F' R","y R' U2 R U R2 F R U R U' R' F' R","y2 x R' U' L U R U' L' U x'","y' r' U' L D' L' U L D x","y2 L' U' L U R U' L' U L R'","y' x' D R U' R' D' R U R' x","y' x' D R U' R' D' R U R'","y R U2 R' U' R U' R' U R U R' U R U2 R'","y2 l' U' L U R U' L' x' F","y2 l' U' L U R U' L' U x'","y x R' U' R D' R' U R D x'","y l' U' R D' R' U R D x'","y B' R' F R B R' F' R","U R U R D R' U' R D' R2","U2 R' F' L F R F' L' F","U' R' U' R' D' R U R' D R2","y F' U R U' L' U R' U' L F","y' R U' R' U2 R U R' U2 R U R' U R U' R'","x L U R' U' L' U R U' x'","r U R' U' r' F R F'","U F R U' R' U' R U2 R' U' F' R' U' R U' R' U2 R","U R' U D' R U2 R' D R' U' R U2 R' U' R2","U2 R U' R2 D' r U2 r' D R2 U' R' U' R U' R'","R' U' R U' R' U2 R U2 R U R' U R U2 R'","y' L' U L U2 R' L' U L U' R","y2 x' R U L' U' R' U L U'","r U R' U' L' U l F'","x' L D R' D' L' D R D' x","R U R' U' L' U R U' R' L","y2 L U L' U L U2 L' R' U' R U' R' U2 R","y2 F U R U2 R' U R U R' F'","y' F R B' R' F' R B R'","R' U' R F R' U R U' F'","r U R' U' z U' R z' R U'","r' U' R U r f' U' f","y' F R U R' U' R U' R' U' R U R' F'"]],
    [25,"OCLL","R' F' r U R U' r' F y'",["y (F' r U R') (U' r' F R)","R U2 R D R' U2 R D' R2","y F' r U R' U' r' F R","F R' F' r U R U' r'","x R' U R D' R' U' R D x'","R' F R B' R' F' R B","y2 R2 D' R U' R' D R U R","y R2 D R' U R D' R' U' R'","y' x' R U' R' D R U R' D' x","y2 R U2 R' U' R U R' U' R U R' U' R U' R'","L' R U R' U' L U R U' R'","y' R U R' U' R' F R U R U' R' F'","y2 l' U' L' U R U' L U x'","L U L' U L U' L' U L U' L' U L U2 L'","y2 F R U' R' U' R U2 R' U' F'","y2 R' F' L' F R F' L F","y R' U2 R U R' U' R U R' U' R U R' U' R U R' U R y' M' U' r' F R F' r U r'","M F R' F' r U R U' R'","L' U' L U' B U' L' U' L U B'","y' R' F' R U R' U' R' F R2 U' R' U2 R","r U2 R2 F R F' R U2 r'","y' R' U2 R' D' R U2 R' D R2","y' x L U R U' L' U R' U'","x U R' U' L U R U' L' x'","U' R U R' U' R' F R U R U' R' F'","y2 x U R D R' U' R D' R'","y2 R' U' R U R' F' R U R' U' R' F R2","y2 x' D R U R' D' R U' R'","U F' r U R' U' r' F R","y2 R U R' U R U' R' U R U' R' U R U2 R'","y2 R' F' R U R' U' R' F R U' R U R' U R","y' L F R F' L' F R' F'","F l' U' L U R U' r'","y L' U2 L' D' L U2 L' D L2","U R U2 R2 D' R U' R' D R2 U' R'","y2 x' r' F r D' r' F' r D x","y F' r U R' U' L' U l","x U R' U' r x' U R U' r'","y f' r U R' U' L' U R E'","y R' U2 R U R' U' R U R' U' R U R' U R","L' U' L R U2 L' U' L U2 R'","M' U' r' F R F' r U r' y M' U' r' F R F' r U r' y2 M' U' r' F R F' r U r' y'","y R L' U' L U R' U' L' U L","U' r U R U' L' U R' U' x'","x U R' U' L U R U' r'","l' U R D' R' U' R D","L' B' R' B L B' R B","x' L' U' R' U L U' R U x","R U R D R' U R D' R' U2 R'","R L' U R' U' L U R U' R'","y2 F R' F' R U R U' R' F R U R' U' F'","R U R' U R U2 R' U2 R U2 R' U' R U' R'","x R' U R D' R' U' R D","y r2 U r' U' r' F r2 U' r' U' r U r' F' U r'","U B' R' F' R B R' F R","U2 R' U' F U F' R F U' F'","y F' L F l' U' L' U l","l' U R D' R' U' R D x'","y2 F R B R' F' l U' l'","y2 r U2 R' U' R U R' U' R U R' U' R U' r'","y F' r U R' U' L' U R","U R2 D R' U R D' R' U' R'","R U2 R' U' R U' R' U2 R U R' U R U2 R'","U2 R2 D' R U' R' D R U R","U' x' R U' R' D R U R' D' x","U F R U R' U' R' F' U' R U R U' R' U' R' U R","R U R D R' U2 R D' R' U' R' U R U R'","R2 U' R U R U' R D' U R U' R' D","U' R' U2 R' D' R U2 R' D R2","R2 D' R U2 R' D R U2 R2 U2 R' U' R U' R'","R U2 R D r' U2 r D' R2","y2 L' B L F' L' B' L F","y' R2 F' R U R U' R' F R U' R' U R","y2 R' F R U R' U' R U R' U' F' U R f R f'","y' R' F R2 U' R' U' R U R' F' R U' R' U R U R'","y' r U R U' r' F R' F'","y x' R U L U' R' U L' U'","U2 R' F' L' F R F' L F","F R' F' L F R F' L'","y F' L F R' F' L' F R","y' r U R U' L' U R' U'","y R' U' R U' R' U R U' R' U R U' R' U2 R","y B' R U R' U' R' F R2 U' R' U' R U R' F' B","y' l U' R' D R U R' D' x","y' R' U' R' D' R U' R' D R U2 R","y2 F R B R' F' R B' R'","y2 F U R' U' R F' R' U R","R' F R U R' U' R' F' R U R","x' R' D R U' R' D' R U"]],
    [26,"OCLL","R U R' U R U2' R' y'",["y R U2 (R' U' R U') R'","y R U2 R' U' R U' R'","R' U' R U' R' U2 R","y2 L' U' L U' L' U2 L","y2 L' U R U' L U R'","R' U L U' R U L'","y' L U2 L' U' L U' L'","U R U2 R' U' R U' R'","y R U2 D2 R' U' R U' R' U2 R D2 R'","y2 U' R U2 R' U' R U' R'","y2 r' F R F' r U R'","y2 z R U R2 U' R' U R' U' z'","B U2 B' U' B U' B'","y' M' U' r' F R F' r U r'","U2 L' U R U' L U R'","U2 L' U' L U' L' U2 L","y2 r' F' r U' r' F2 r","y2 L' U' L U' L' U2 L y2"]],
    [27,"OCLL","R U2' R' U' R U' R'",["(R U R' U) (R U2 R')","R U R' U R U2 R'","y' R' U2 R U R' U R","y L' U2 L U L' U L","y2 L U L' U L U2 L'","R U' L' U R' U' L","y F U F' U F U2 F'","y' U R U' L' U R' U' L","y' R U' R' U' R U' R' U' R U' R' U' R U R'","y' R' U2 R U R' U R y","y2 U R' U2 R U R' U R","U L' U2 L U L' U L","R U' r' F R' F' r","r U' r' F R' F' r U M","U' R' U2 R U R' U R","y r' F2 r U L' U L"]],
    [28,"All Corners Oriented","R U R' U' M' U R U' r'",["(r U R' U') M (U R U' R')","r U R' U' M U R U' R'","R' F R S R' F' R S'","r U R' U' r' R U R U' R'","y2 M' U M U2 M' U M","M U M' U2 M U M'","y' M' U' M U2 M' U' M","S' R U R' S R U' R'","r U R' U' r' F R2 U' R' U' R U R' F'","y M U' M' U2 M U' M'","y' r' U' R U M' U' R' U R","U' M' U' M U2 M' U' M","y' S' R U' R' S R U R'","M' U' M U' M' U' M U' M' U' M","y2 f U R U' R' S' R U R' U' F'","U r' U r2 U' r2 U' r2 U r2 U r2 U' r2 U' r2 U r'","y2 r2 D' r U' r' D r2 F' r' U r F","U' r' U' R U M' U' R' U R","y r U R' F' R U R' U' R' F R2 U' r'","y' r' R2 U' R' U M' U' R U R'","L R F R2 F R' L D' R2 D2 F2 L2 B2 U' R2 B2","y M' U M U M' U M U M' U M","F R' F' R L' U R U' R' L","R L' B L R' U2 R L' B L R'","y F U R U' R' F2 U' L' U L F","M' U' M U' M' U' M U' M' U' M","r U R' U' r' U2 R U R U' R2 U2 R","M2 U' M U2 M' U' M' U' M' U2 M U' M'","y2 r U' r2 U r2 U r2 U' r2 U' r2 U r2 U r2 U' r","y2 M' U r' R U2 M' U r' R","F R U R' U' F2 L' U' L U F","U' R U R' F' R U R' F' R U R' U' R' F R2 U' R' U' F R U' R'","R U R' U' M' U R U' r' R U R' U' M' U R U' r'","F R U R' U' F' U2 F R U R' U' F'","y' M U R U R' U' M' U R U' R'","y l' U' L U l L' U' L' U L","U r U R' F' R U R' U' R' F R2 U' r'","y' r U' r' U' r U r' R U2 R' r U' r' U r U r'","y' M U M' U M U M' U M U M'","R F D2 r2 D2 F r2 D2 R","y' M R U R' F' R U R' U' R' F R2 U' R' U' M'","y' L R' F' L' R U2 L R' F' L' R","y l' U' L U M U' L' U L"]],
    [29,"Awkward Shapes","M F R' F' R U R U' R' U' M'",["y (R U R') U' (R U' R') (F' U' F) (R U R')","r2 D' r U r' D r2 U' r' U' r","y R U R' U' R U' R' F' U' F R U R'","y S' R U R' U' R' F R F' U S","M U R U R' U' R' F R F' M'","y l D l' U l D' l2 U l U' l' U' l","y2 R' F R F' R U2 R' U' F' U' F","y r U R' U' M r' F R F' M'","y' R U2 R2 F R F' R U' R' U R U2 R'","y2 R2 U' R F R' U R2 U' R' F' R","y2 F' U' L' U2 L U L' U2 L U F","y R' U2 R2 U R' U' R' U2 F R F'","y' r D r' U r D' r2 U r U' r' U' r","y R F R' U R F' R2 F R U' R' F' R","y r U R' U' M2 R' F R F' M'","y2 R' F R U' R' U R U2 R' U' F' U2 R","y l D l' U l D' l' R' F R U' R' F' R","y R U R' U' R' F R F' R U R' U' M' U R U' r'","y2 F R' U' R2 U' R2 U2 R U' F'","y' f U R U' R' f' R U R' U' R' F R F'","y' R U R' U R U2 R' U R U R' U' R' F R F'","y2 F' r U' r2 F r U r' F' r F2","y R' F R' F r U' R U' R U' r' F","R' U' R U' R' U2 F R U R' U' F' U R","y r U R' U R U2 r' L' U' L U' L' U2 L","U R U R' U' R' F R F' R U R' U' M' U R U' r'","y R U' R' U2 S R' F R f' U R U' R' U R U R'","y' S r B r' f' r B' r' U F","L2 U' L B L' U L2 U' L' B' L","y2 l2 D' l U l' D l2 U' l' U' l","U R U R' U' R U' R' F' U' F R U R'","y2 R' F R F' R U2 R' U' y' R' U' R","y F R U R' U' F' U2 R U R' U' R' F R F'","f' L' U' L2 U L U' L2 U L f","f' r' F' r U S r U R' U' r' F R","y2 R' U' F U R U' R' F' U2 R U R' U R","f' L' U' L U S r U R' U' r' F R","y2 R' F R F' R U2 R' d' L' U' L","y L' U' L U L F' L2 U L U L' U' L U' L' U L F","y2 R' F R F' R U2 R' U' y L' U' L","y F R U R' U' F' L' U' L U L F' L' F","r D r' U' r D' r' U r' U' R U M'","y R U R' F' U' S' F R U' R' S","r' R U R U R' U' R' F R F' M'","L2 U' L B L' U L2 U' r' U' r","y2 F' z R' U' R2 U R U' R2 U R F z'","x' U' R U' R2 F x R U R' U' R B2","y x R' U' R D' R' U2 R' U' R2 D x'","y2 F' L F' L2 U L U L' U' L F2"]],
    [30,"Awkward Shapes","F U R U2' R' U R U2' R' U' F' y2'",["y2 F U (R U2 R') U' (R U2 R') U' F'","y' r' D' r U' r' D r2 U' r' U r U r'","y2 F U R U2 R' U' R U2 R' U' F'","y2 F R' F R2 U' R' U' R U R' F2","y S' R' U' R f R' U R U' F'","y' R U R' U' R' F R2 U' R' U' R U R' U R U' R' F'","f R U R2 U' R' U R2 U' R' f'","y' S U2 F R U' R' U R U R' f'","y' S L' U' L U L F' L' F U' S'","l2 D l' U' l D' l2 U l U l'","y' r U2 R2 F R F' R U' R' U R U2 r'","y2 F U R U' R2 F' R U R U' R' F R U R' U' F'","y' R' F' r U M R U' r' F M'","y2 R U R' U R U' R' F' U' F U R U2 R'","R2 U R' B' R U' R2 U R B R'","y2 r2 D r' U' r D' r2 U r U r'","y' L' U' L U L F' L' F R U R' U' M' U R U' r'","U' F R U' R' U R U R' U R U' R' U R U' R' F'","U' r' D' r U' r' D r2 U' r' U r U r'","R U R' U R U' R' U R U' B U' B' R'","f R U R' U' S' R' F' r U R U' r'","U M f R f' U' r' U' R U M' U M'","y' L' U' L U L' U L F U F' L' U' L","M U' L' U' L U L F' L' F M'","y' l' U' L U' L' U2 l R U R' U R U2 R'","y2 R U R2 F' R U R U' R' F U' R' F R F'","y R2 U' S' U2 S U' R3 U R' U' R' F R F'","R U R' U R U' R' U R U' y R U' R' F'","y' D R U' R' D' R' F R F' R U R' U L' U L U2 L' U L","y' D R U' R' D' R' F R F' R U R' U r' F r U2 r' F r","y' l' U' L U M l F' L' F M'","y2 L F' L' F L' U2 L U y L U L'","U2 F U R U2 R' U' R U2 R' U' F'","y S' R' U' R U R f' U' f U' S","y' x L U L' D L U2 L U L2 D' x'","y L' U2 L2 F' L' F L' U L U' L' U2 L","l L' U' L' U' L U L F' L' F M'","y2 L F' L' F L' U2 L U F U F'","y2 M' U' R' U' R U R B' R' B M","y2 R U R U' R' F U R2 U' F' R' U R","y' F' L' U' L U F R U R' U' R' F R F'","y' L' F' L U' L' F L2 F' L' U L F L'","y S' F R U' R' U R U R' F' U2 S","y' R' F' r U r' R2 U' r' F M'","y2 L2 U L' F' L U' L2 U L F L'","R2 U R' B' R U' R2 U l U l'","y' L U2 L2 U' L U L U2 F' L' F"]],
    [31,"P Shapes","R' F R U R' U' F' U R",["(R' U' F) (U R U' R') F' R","R' U' F U R U' R' F' R","y2 S' L' U' L U L F' L' f","y S R U R' U' f' U' F","y' F R' F' R U R U R' U' R U' R'","y2 S' r' F' r U r U' r' f","y2 r' F' U F r U' r' U' r","y2 F f' L' U' L U L F' L' f y2","y2 L' U' B U L U' L' B' L","R' d' L d R U' R' F' R","y' R' U r' D' r U' r' D r U' R","y2 R' F R U R' U' F2 U F R","M' f R f' U' r' U' R","F' U' L' U L F l' U' L U l F' L' F","R' U f R U R' U' f' U2 R","y' R' U' r' D' r U r' D r R","y' F R U R' U' R U R' U' F' R U R' U R U2 R'","y2 F R' F' R U2 R' F R F' R U2 R'","r U2 R' U' R2 U' L' U R' U' x'","y' M' U' L' U' L U L F' L' F U M","M' U R U' M U2 R' U' F' U' F","z D' R' F z' U R U' R' F' R","y2 L' U2 L U F U' F' L' U L","U2 S' L' U' L U L F' L' f","y' F U R U' R' F2 r U R' U' r' F R","R' U' F U R U' R' F' R","z' U' L' F L U L' U' F' U"]],
    [32,"P Shapes","f R' F' R U R U' R' S'",["S (R U R' U') (R' F R f')","S R U R' U' R' F R f'","y2 L U F' U' L' U L F L'","R U B' U' R' U R B R'","y' R' F R F' U' r U' r' U r U r'","y2 x' R U' R' D R U R U' R' U R' D' x","y F U R' U' F' U F R F'","y2 F U R U' R' F' r U R' U' r' F R F'","R U2 R' U' F' U F R U' R'","y R U' r D r' U r D' r' U R'","U2 L U F' U' L' U L F L'","y2 x' r U F' U' r' F r F r' x","y' F' L F L' U' L' U' L U L' U L","y2 z U R F' R' U' R z' r U r'","l F U' F' l' U l U l'","y' R' U' F D U R U' R' D' F' R","F' f R U R' U' R' F R f'","R d L' d' R' U l U l'","y2 L d R' d' L' U L F L'","y R U2 R2 U' F' U F R2 U' R'","U2 L U F' U' L' U r U r'","y' M' U R U R' U' R' F R F' U' M","y S' r' F' r U f U F'","y' F' r U r' U' r' F' r U r' F r","y R U r D r' U' r D' r' R'","y2 r B U' B' r' U r U r'","y2 F U R U' F' r U R' U' r'","S R U R' U' R' F R F' S'","S R U R' U' R' F R f' R U R' R U' R'","y' F' r U r' U' L' U' L U L' U L","y' R' U2 R U R' U2 F' U' F R U R' U2 R","U' R' U2 R U R' U2 F' U' F R U R' U2 R","y S' L' U' L U f U F'","y2 z u' R2 U R U2 R D R' U R z x'","y2 z u' R2 U R U2 R D R' U R z' x'","l F U' F' R' F R U l'","y f' U f R' U' R' U' R U R' U R","y' F R' F' r U R U R' U' R U' r'","y2 R' F' U F R U' r' U' R U M'","y x' U' R U l' U' R' U' R U R' U R","y R D r' U r D' R' f R' f'","R U B' U' R' U l U l'","U2 L d R' d' L' U L F L'","f F' R U R' U' R' F R f'","y2 x' R U R' D R U' R U' R' U R' D' x","y x' U' R U R' x U' R' U' R U R' U R","U' F R' F' r U R U R' U' R U' r'","r' U2 R U R2 U L U' R U x"]],
    [33,"T Shapes","F R' F' R U R U' R'",["(R U R' U') (R' F R F')","R U R' U' R' F R F'","y2 L' U' L U L F' L' F","y2 r' F' r U r U' r' F","R U R' F' U' F R U' R'","y r U r D r' U' r D' r2","R U R' U' l' U R U' x'","U2 L' U' L U L F' L' F","x Lw U R' U' Lw' U R U'","R' U' R U R f' U' f","y' r' U' r' D' r U r' D r2","F R U' R' U R U R' F'","y' f R f' U' f' U f R'","R U R' U' R U' B' R B R2","R' U' R U R' U F R' F' R2","y F U F' U' F' r U r'","y2 F' L' U L U' L' U' L F","M' U2 M U' y' F R F' R U R' U' R'"]],
    [34,"C Shapes","F U R' U' R' F' R U R2' U' R' y2'",["y2 R U R2 U' R' F (R U R U') F'","y f R f' U' r' U' R U M'","y2 R U R2 U' R' F R U R U' F'","F R U R' U' R' F' r U R U' r'","y2 R U R' U' B' R' F R F' B","y2 R U R' U' y' r' U' R U M'","y2 R U2 R2 F R F' R U' R' U' R' F R F'","S U S R' U' R U R f' U' F S'","R' U' R U F R f' U' S","y2 R' U2 R2 U R2 U R U2 R' F R F'","R U2 R' F R U R' U' F' U R U R'","y' R2 D' R U' R' D F R F' U R","R U2 R' U R' F' U' F U R2 U R'","y2 R U R' U' R' F R F' U R U R' U R U2 R'","U2 R U R' U' B' R' F R F' B","y2 R U R' U' x D' R' U R E'","y F R' F' R U R U R2 F R F' R U2 R'","y R U R' U' M2 R' F R F' M' U' M'","y2 R U R' U' y R' F' R M' U M","y2 R U2 R' U' R' F' U' F R2 U' R2 U2 R","R' U' R U y' l U L' U' M'","y' F U F' L' U2 L U' F' r U2 R' U R U2 r'","r U2 R' U' R U2 r' F U L' U2 L F U' F'","y2 R U R' U' y' r' U' R U R' r","R' U' R M U f R f' U2 M'","y2 R U R' S R' F R f' U R U R'","y2 R U R' M' U' F' U' F U2 M","y2 R U R' U' y R' F' r U r' R","y2 R U R' U' f' U' F U S","y' f' L' f U l U L' U' M'","x U2 R2 U r' U' r B U' R2 U2 x'","y R U R' U2 F2 U' r' F r2 U r' F","y F' U' F U r U R' U' M","y R' U' F U R U' S R' F' R S'","y2 R U R' U' x D' R' U R U' D x'","y2 L' U' L U L F' L' F U' L' U' L U' L' U2 L","R U R' U' R' F R F' R' U' R U' R' U2 R","y R u R' u' y2 x2 y2 x2 u R u' R' F' U' F U r U R' U' M","R U R' F' R U R' U' R' F R U R U' R' U' R' F R F'","y2 R U R' U' B' R' F R S y' x","y2 R U R' U R U2 R' U' F R U' R' U' R U R' F'","y2 R U R' U' y R' F' r U M","y2 R U R' U2 L' U R' F R F' U' L","L U L2 U' L' B L U L U' B'","U2 R U R2 U' R' F R U R U' F'","R' F R f' U' r U' r' U r U r' S","F' L' U' L U L F l' U' L' U l","F R U R' U' F' U F' r U R' U' r' F R","y2 R U R' U' R' F R F' R' U2 R U R' U R","y2 R U R' U' y R' F' r U R r'","y2 R' U2 R U R' F' U' F U R U2 R' U' R","U2 R U R' d' l' U' L U L' l","y2 L' U' L d r U R' U' R r'","y2 L' U' L U y l U L' U' M'","U f R f' U' r' U' R U M'","y2 R U R' d' l' U' L U L' l","y2 R U R' U' f' y U' L U M","U2 R U R' U' M' U R U' r' R U R D R' U' R D' R2","y2 R U R' U' M' U R U' r' R U R D R' U' R D' R2","R' U' R U F R B' R' F' B","y2 R U R' d' l' U' L U r' R","y' F U F' U' R' F' r U M","R' U' R U y r U R' U' r' R","R' U' R y U r U R' U' M","y2 R U R' U' B' R' F R S","y' F U F' U' R' F' L F L' R","L U L' U' y' R' F' L F M","y2 R U R' U' y' r' U' R U r R'","y2 F R U R' d' x U2 R2 F R F' R U2 r'","F R F' r U R' r' R U R' U' r U' r'"]],
    [35,"Fish Shapes","R U2' R' F R' F' R2' U2' R'",["(R U2 R') (R' F R F') (R U2 R')","R U2 R2 F R F' R U2 R'","f R U R' U' f' R U R' U R U2 R'","R U2 R' d' R' F R U' R' F' R","y L' U2 L2 F' L' F L' U2 L","y' R' U' F R' F' R2 U' R' U2 R","R' U2 R U R' U R U2 F R U R' U' F'","F' U2 F U r U' r' U r U r'","y R2 D r' U r D' r' U' R' U M'","y' R' U2 R l U' R' U l' U2 R","y R U2 R' U' R U' R' U' R U R' U' R' F R F'","y2 F R' F' R2 U R' U' L' U R U' R' U R U' R' L","y2 F U R U' R' F' U2 R U R' U R U2 R'","y' R' U2 R y U r U' r' U r U r'","y' R' U2 R U y r U' r' U r U r'","U' x' R' F2 R2 U' R' U R' F2 R x","R U2 R2 x U R U' R x' U2 R'","y2 R2 F R F' R U2 R' U R U2 R' U' R","F' U2 F2 R' F' R F' U2 F","y' R' U2 l R U' R' U l' U2 R","y2 F R' F' R2 U' R' U2 R U' R' U2 R U R'","y' R U2 R' U' R U' R' U2 F R U R' U' F'"]],
    [36,"W Shapes","F' L F L' U' L' U' L U L' U L y2'",["y2 (L' U' L U') (L' U L U) (L F' L' F)","y R U R2 F' U' F U R2 U2 R'","y2 L' U' L U' L' U L U L F' L' F","y2 R U R' F' R U R' U' R' F R U' R' F R F'","y2 R' F' U' F2 U R U' R' F' R","R U R' U' F' U2 F U R U R'","R' U' R U' R' U R U l U' R' U x","R' U' R U' R' U R U R f' U' f","R U2 r D r' U2 r D' r' R'","R U R' U2 F' U' F U' R U' R'","y2 r' F' r U' r' F r U r U' r' F","R' U' R U' R' U R U R B' R' B","U R U R2 F' U' F U R2 U2 R'","R U R' U R' F R F' U' R U R' U' R U' R'","y2 R' U' R U' R' U2 R U' F R U R' U' F'","y2 r U' r2 D r2 U' r2 U r2 U D' r'","R' U' R U' R' U2 R2 U R' U' R' F R F'","y F R U R' U' R U R' U' R' F' r U R U' r'","L' U2 L r U2 R' U' R U2 r' F","R' U' R U' R' U R U l U' R' U","y F R' F' R U R U R' U' R U R' U' R U' R'","R U B U' B' U2 R' U' R U' R'","y' R U' R' U' F U R U' R' F' R U2 R'","R' U' R U' R' U R U R y R' F' R","y' f R U R' U' f' R' U' R U' R' U2 R","y2 L' U' L U' L' U L U r U' r' F","L U L' B' L U L' U' L' B L U' L' B L B'","y2 L U2 l D l' U2 l D' L' l'","L' U' L U' L' U2 L U F R U R' U' F'","F R U R' U' F' U' r' U2 R U R' U r","y F U R U' R' F' U' R U2 R' U' R U' R'","U2 L' U' L U' L' U L U L F' L' F","y2 l' U' L U' L' U L U R U' r' F","R' F' U2 F R U2 R' U' R U2 R' U2 R","F U2 r U2 r' F U2 F2 U2 F r U r'","R U2 R2 F2 r U' R U2 r' F","R' U' R U' R' U R U R x' U' R' U x","R U R' d' L' U2 L d R U R'","U2 l' U' L U' L' U2 l R U R' L' U2 R U' R' U2 L U R U' R'","U2 R' F' r U' r' F2 U' R U R' U' R2 D R' U R D' R' U2 R' U R","U2 R U R' F' R U R' U' R' F R U' R' F R F'","y2 l' U' L U l F' L' U' L' U L F","R' U' R U' R' U R U x' R U' R' U","y' R U R' U' R' U' F R F' U' R' U2 R","R' U' R U' R' U R U y F R' F' R","y2 R' U' R U' R' U2 F' U' F U R"]],
    [37,"Fish Shapes","F R U' R' U R U R' F'",["F R (U' R' U') (R U R') F'","F R' F' R U R U' R'","F R U' R' U' R U R' F'","y F' r U r' U' r' F r","y2 r2 D' r U' r' D r U r","R' F R F' U' F' U F","y r U' r' F d R U' R'","R U R' U' R' F R F' R U R' U' R' F R F'","R' F R F' y U' L' U L","y' R U2 R' F R' F' R2 U2 R'","R' F' U F U F' U' F R","y F' L F L' U' L' U L","x U R' U' l U R U' R'","R' U' R B U' B' R' U R","y L F' L' F y' U R U' R'","d F R U' R' U' R U R' F'","y2 B L U' L' U' L U L' B'","y M' U' M R' F R U y' R U' R'","F l' U' l U l F' l'","U' R U2 R' F R' F' R2 U2 R'","y2 F R U R' F' U' F' r U r'","y2 F R U R' F' U' F' L F L'","U F' r U r' U' r' F r","M' U R U' r' y U' L' U L","y r2 D r' U r D' r' U' r'","y L F' L' F U F U' F'","y' R U R' F' U F R U' R'"]],
    [38,"W Shapes","F R' F' R U R U R' U' R U' R'",["(R U R' U) (R U' R' U') (R' F R F')","R U R' U R U' R' U' R' F R F'","y F R U' R' S U' R U R' f'","r U R' U' r' F R U R U' R' F'","y2 L U L' U L U' L' U' L' B L B'","y2 R U R' U R U2 R' U F R U R' U' F'","y2 L' U2 l' D' l U2 l' D l L","y2 L U L' U L U' L' U' x' L' U L U'","l' U l2 D' l2 U l2 U' l2 U' D l","y2 L' U' L U F U2 F' U' L' U' L","r U R' U R U' R' U' r' F R F'","U2 F R U' R2 F R F' U' F2 r U r2 F2 r","y2 r' F' r U F U2 F' U' r' F' r","L' U' L F L' U' L U L F' L' U L F' L' F","R' U2 r' D' r U2 r' D R r","U L' U' L2 F U F' U' L2 U2 L","y F R U' R' F' B z U' R U R' f'","y R' F R2 U R' U' R' F R2 U' R' U' R U R' F' R' F' R","U' F R U R' U' F' U' S R U R' U' R' F R f'","y' R' U' R2 B U B' U' R2 U2 R","z' U L U' L U L' U' L' U' F U F'","y R U R' F' R U R' U' R' F R2 U' R' F R U R' U' F'","R U R' U R U' R' U' R' x U R U' x'","y2 R U R' U F' U F U2 R U' R'","y2 L U L' U L U' L' U' y2 R' F R F'"]],
    [39,"Lightning Shapes","L U F' U' L' U L F L' y'",["y L F' (L' U' L U) F U' L'","y' f' r U r' U' r' F r S","y' R U R' F' U' F U R U2 R'","y L F' L' U' L U F U' L'","y' f' L F L' U' L' U L S","F R' F' U' F U R U' F'","y F R U R' U' F' R' U' R U' R' U2 R","y' R B' R' U' R U B U' R'","r U R' U R' F R F' U2 r' F R F'","y' F R U R' U' R U R' U' R U' R' U' R U R' F'","y2 M F R' F' R U R U' R' U' M'","y2 f R' F' U' R' U R S'","y' S' U' F R' F' R U R U' R' S","y2 L' l' D' l U' l' D l U L","U' f' L F L' U' L' U L S","y2 r' R F R' F' R U R U' R' U' M'","y f' U' L' U L f R' U' R U' R' U2 R","R' r' D' r U' r' D r U R","y R U2 R' U' R U' R' F U R U' R' F'","y F' U f R' U' R' U R S'","y' R U' r' U' F' U F M'","y r U' r' U' r B U B' r'","y' l U' R' F' R F U F' l'","U' F R U R' U' R U R' U' R U' R' U' R U R' F'","y' R U R' U R U R' U2 R U R' U2 R U R2 F R F'","y L F' L' U' L U b L' D'","F U F' L' U' L U F U2 F'","y R U R' U' F2 L F L' F U' R U R'","y' F' L' U' L U F L' U' L U' L' U2 L","y' F' L' U' L U F U' R U2 R' U' R U' R'","y L F' L' U' L d R d' L'","U F R U R' U' F' R' U' R U' R' U2 R","y r U' r' z R' U R F R' U'","U' R U R' F' U' F U R U2 R'","y r U' r' U' L U F U' L'","y' R U' r' y' U' R' U R S'","y2 f R f' R' U' R U f R2 f'","y r U' r' U' r y R U R' f'","y r U' r' U' r f R f' r'","y L F' L' U' L U y' R d' L'"]],
    [40,"Lightning Shapes","R' U' F U R U' R' F' R y'",["y R' F (R U R' U') F' U R","y R' F R U R' U' F' U R","y' f R' F' R U R U' R' S'","R r D r' U r D' r' U' R'","y' L' U' L F U F' U' L' U2 L","y R U R' F' U' F R U R' U' R U' R'","M F' L F L' U' L' U L U M'","y' f l' U' l U l F' l' S'","U F R U R' F' R' F U' F' U R","y' F R U R' U' F' R U R' U R U2 R'","l L' F' L F L' U' L' U L U M'","y' r' F R U F U' F' M'","r' R F' r U r' U' r' F r U r R'","y' L' B L U L' U' B' U L","B' R B U B' U' R' U B","y l' U l U l' f' L' f l","y' S F R' F' R U R U' R' S'","r' R F' r U r' U' r' F r U M'","y R U R' U R U' R' U' M' U2 R U' R' U R U2 r'","U R' F R U R' U' F' U R","U' R U R' U' R' F R F' r U R' U' r' F R F'","y R' F R U R' U' y L' d R","M F' r U r' U' r' F r U M'","y2 F' U f z' r B r' U' S' z","y' f R U' R' U' R U R' F' U2 S'"]],
    [41,"Awkward Shapes","F U R U' R' F' R U2' R' U' R U' R' y2'",["y2 (R U R' U) (R U2 R') F (R U R' U') F'","y2 R U R' U R U2 R' F R U R' U' F'","y2 F U R2 D R' U' R D' R2 F'","y' S U' R' F' U' F U R S'","M U' F' L' U' L U F M'","y2 R' F' U' F R S' R' U R S","y R U2 R' U' R U' R2 F' U' F U R","y2 M' R' F' U' F U R U' M","y' R U R' U R U' R' U R U' R' U' R' F R F'","F R U' R' U2 S' R U R' F' S","R' M2 U' F' U F r U' M'","y' S F' L' U' L U F U' S'","R U' R' U2 R U f R' f' U' R'","y2 F R' F' U2 R U R U' R' U R' U R","R U' R' U2 R U B U' B' U' R'","f R U R' U' f' U' R U R' U R U2 R'","U' r U R' U R U' R' U R U' R' U' L' U l F'","r' M U' F' U F r U' M'","y' F' L F L' U2 L U L2 U L2 U2 L'","L U L' U L U2 L' B L U L' U' B'","y L U2 l' U l U' l' U' l U' L' U L U2 L'","y' L F' L' F L F' L' F L' U' L U L' U' L y","y2 F R' F' R U R U' R2 U2 R U R' U R","y2 r' M2 F' U' F U R U' M","y R U2 R' U' R U' R2 y L' U' L U F","y' F' L' U' L U F R U R' U' M' U R U' r'","y2 L' U' L S' F R U R' S F'","y R U2 R' U' R U' R' U' F R U R' U' F'","U2 R U R' U R U2 R' F R U R' U' F'","y2 r R2 F' U' F U R U' M","y' r U2 R' U' R U' r' U' R U R' U R U2 R'","y2 F U R U' R' F' U R U R' U R U2 R'","y2 R U R' U R U2 R' U R' F' U' F U R","y2 F U2 F' U' F U' F2 L' U' L U F","y2 U' R U2 R' U' R U' R2 y' R' U' R U B","L U L' U L U2 L' F' L' U' L U F","y' L F' L' F L F' L' F L' U' L U L' U' L","R U' R' U2 R U y R U' R' U' F'"]],
    [42,"Awkward Shapes","F U R U' R' F' R' U2' R U R' U R",["(R' U' R U') (R' U2 R) F (R U R' U') F'","R' U' R U' R' U2 R F R U R' U' F'","y F S' R U R' U' F' U S","y R' F R F' R' F R F' R U R' U' R U R'","y R' U' F2 u' R U R' D R2 B","y F R' F' R U2 R' U' R2 U' R2 U2 R","M U F R U R' U' F' M'","y F R f' R' F' U' F R U' S","y R U R' U' M' U R U' r' F R U R' U' F'","y' R' U2 r U' r' U r U r' U R U' R' U2 R","y F R' U D' R U' R' D R U R' U' R2 U R' U' R U R' U' F'","y' R' U R U' R2 F' U' F U R U' R U' R' U R","y S' U L F U F' U' L' S","y2 R' U R U2 R' U' F' U F U R","y R' F R U R' F' R F U' R U R' U' F'","y2 L' U' L U' L' U2 L F' L' U' L U F","r' F r U2 r' F' U' F U F r","y F R U R' U' F' R U R' U' R' r U R U' r'","y F R U' R' U' R U R' F' R U2 R' U' R U' R'","f' L' U' L U f U L' U' L U' L' U2 L","R B U B' R' S' R U' R' S","B' U' R2 D' R U R' D R2 B","U F R' F' R U2 R' U' R2 U' R2 U2 R","y R' U2 R U R' U R U F R U R' U' F'","y2 F' U' L' U L F U2 R U2 R' U' R U' R'","y R' F2 r U r' F R2 U2 R' U' R U' R'","M R B U B' U' R' U M'","y F R U R' U' F' R U R' U' M' U R U' r'","y2 F' U' L2 D' L U L' D L2 F","y2 R U2 R' U' R U' R' F U R U' R' U R U' R' F'","y2 R U' R' U R U' R' U' R U' B U2 B' R'","U l' U' L U' L' U L U' L' U L U R U' r' F","y' S U2 F R U R' U' F' U' S'","y2 L' U' L U' L' U2 L U2 F R U R' U' F'","y' x' L' U L U' L' U L U' x L U L' U' L U L'","R' F2 R2 U' F U' F' U2 R2 F2 R","y x R' U R U' R' U R U' x' R U R' U' R U R'","y' R' U' R U' R' U R U' R' U R U R B' R' B","r' R2 B U B' U' R' U M'","y f' F2 R U R' U' F' U S","y r' U' M' F R' F' R2 r' U r","R' U' R U F R U R' U' R' U R U' F'","y' L' U2 L U L' U L U' F R U R' U' F'","R' U' R U' R' U2 R U R' F' U' F U R","y L' U' L U' L' U L U' L' U L U L F' L' F","y F R' F' R U R U' R' r' F' r U' r' F2 r","y r' U' r R' F R' F' R2 r' U r","y f R f' M' R' F' U' F M R","y2 R U R' S F' L' U' L S' F","y R' U' F' U F R U' R U2 R' U' R U' R'","R' U' R U' R' U2 R B' R' U' R U B","y2 F' U2 F U F' U F2 R U R' U' F'","y R' U2 R U R' U R2 B U B' U' R'","y R' U2 R U R' U R2 y R U R' U' F'","L' U L U2 L' U' y' L' U L U F","y R' U' F2 u' R U R' u F2 R"]],
    [43,"P Shapes","f' U' L' U L f",["y R' U' (F' U F) R","y R' U' F' U F R","y2 F' U' L' U L F","f' L' U' L U f","B' U' R' U R B","y' r' F' U' F U r","U R' U' F' U F R","y' R U R' F' L' U' L F","y2 R' U' F R' F' R U R","y' R U R' F' U2 F R U' R'","r' U' R' F R F' U r","y2 b' R' U' R U b","y2 F' U' r' F r F","y2 R' U2 R U R' F' U F R","y F' L' U L F R U' R'","x' U' F' R' F R U x","y2 f R f' R' F' U' F R","y' L' d' R' U R B","y F U R U' R' F' R U2 R' U' R U' R'","y R U' R' U' F' U2 F U R U' R'","y2 z F' R' U' R U F z'","U2 F' U' L' U L F","y2 R2 F R F' R U2 R' F' U2 F R"]],
    [44,"P Shapes","f U R U' R' f'",["f (R U R' U') f'","f R U R' U' f'","y2 F U R U' R' F'","y R U B U' B' R'","y' L U F U' F' L'","y2 x U' L U2 R' U' M U' L' U L U2 R U2 R'","y' F R U' R' U2 R U R' F'","y' F R U' R' F' L' U L","y2 F U R U' R' F'","y L' U' L F R U R' F'","y2 z' F L U L' U' b'","B U L U3 L3 B3","f R U R3 U3 f3","B L' B' L U B' U F U R' U' R F' B","B L' B' L U B' U' B L F U' F' L'","B' U R B' R' B U F U R' U' R F' B","B' U R B' R' B U' B L F U' F' L'","B' R' B L' B' R U B U B' U' B L","B' R' B L' B' R U B U' L F U' F'","B' D B U R U B U' B' R' B' D' B","B' D B2 U L U' L' B' U B' D' B","B' D' B U R U B U' B' R' B' D B","B' D' B2 U L U' L' B' U B' D B","R U B' R B R' U' R'","U2 F U R U' R' F'","y2 R B R' U2 R U R' U R U' B' U' R'","f R2 D R' U R D' R2 U' f'","y2 r U x' R U' R' U x U' r'","R U2 R2 F R F' U' R U' R'"]],
    [45,"T Shapes","F U R U' R' F'",["F (R U R' U') F'","F R U R' U' F'","y R' F' U' F U R","y2 f U R U' R' f'","y2 F' L' U' L U F","f' U' L' U L f","y' r' U' F' U F r","y' R B U B' U' R'","U2 F' L' U' L U F","U R' F' U' F U R","y L F U F' U' L'","y' R f R f' U' R'","B' R' U' R U B","y2 B L U L' U' B'","F R2 D R' U R D' R2 U' F'"]],
    [46,"C Shapes","R' U' F R' F' R U R",["R' U' (R' F R F') U R","R' U' R' F R F' U R","R' F' U' F R U' R' U2 R","y F R U R' U' F' U' R U R' U R U2 R'","l' U2 L2 F' L' F U L' U l","y2 r' U' F R' F' R U r","y2 L U L F' L' F U' L'","R' F' U' R U R' U' R' F R2 U' R' U R","R' U' l' U R U' x' U R","y' F R U R2 U' R F' U' R' U2 R","y2 L F U' R U R' F' L'","y2 r' F' r' F r U' F r","y F R U R' y' R' U R U2 R'","M F U R U' R' F' U' M'","y F R U R' F' U F U2 F'","R U R' U R U' R' F' U F R U' R'","y' R U R2 U' R' F R2 F' R' U R","y' F R U R' U' F' U R' U' R U' R' U2 R","y' F R U R' U' F' U2 R U2 R' U' R U' R'","y2 f R U R' U' f' r U R' U' r' R U R U' R'","y' x' U' R' F' R U F' U' F2 U x","y2 r U2 R2 F R F' U' R U' r'","R U R B' R' B U' R'","y F U F R' F' R U' F'","R U x' R U' R' U x U' R'","R2 D r' U' r D' R2 F' U F","y2 r' F' L' U L U' F r","y F R U R' F' d R U2 R'"]],
    [47,"L Shapes","F' U' L' U L U' L' U L F",["F' (L' U' L U) (L' U' L U) F","y' F R' F' R U2 R U' R' U R U2 R'","F' L' U' L U L' U' L U F","R' U' R' F R F' R' F R F' U R","y' R' F' U' F U F' U' F U R","y2 f' U' L' U L U' L' U L f","U' F R' F' R U2 R U' R' U R U2 R'","y2 S' R U2 R2 U' R2 U' R2 U2 R S","F' r' F' r U r' F' r U F","y' F U R U' R' F' R U R' U R U2 R'","y2 R U R2 F R F' U f R' F' R S'","R' U' l' U R U' R' U R U' x' U R","U2 f' U' r' F r U' r' F r f","b' U' R' U R U' R' U R b","R' F' r U' r' F2 R2 U2 R' U' R U' R'","y2 B' R' U' R U R' U' R U B","y' R' F R F' R U' R' U R U' R' U2 R U' R2 F R F' R U' R' U R U' R' U2 R U' R'","L' U2 L U L' U' L U2 L F' L' F","L F' L' F U2 F U' F' U F U2 F'","z F' U' R' U R U' R' U R F z'","y2 R B' R B R2 U2 f R' F' R S'","y2 f' U f U2 R' U' R U' R2 U2 R","y f' U f U2 R' U2 R' U2 F R F'","z F' U' R' U R U' R' U R F","y' x U R' U' R x' U2 R U' R' U R U2 R'","R' U' x R' U R U' R' U R U' x' U R","y' R' z x U' R' U R U' R' U R F"]],
    [48,"L Shapes","F U R U' R' U R U' R' F'",["F (R U R' U') (R U R' U') F'","F R U R' U' R U R' U' F'","y2 f U R U' R' U R U' R' f'","R U2 R' U' R U R' U2 R' F R F'","F R' F' U2 R U R' U R2 U2 R'","y2 R U R' U R U2 R' U' F R U R' U' F'","y' R U R' U R' F R F' R U' R' U R U2 R'","y2 B L U L' U' L U L' U' B'","r U2 R' U' R U R' U2 r' F R F'","y2 R U R' U R U2 R2 F' U' F U R","R' U' F' U F R2 U2 R' U' R U' R'","y' f U' f' U2 x' r U2 r B2 U' r' F","y F' r U r' U2 r' F r U' r' F2 r","z' F U L U' L' U L U' L' b'","y' R B U B' U' B U B' U' R'"]],
    [49,"L Shapes","r' U r2' U' r2' U' r2' U r' y2'",["y2 r U' (r2 U) (r2 U) (r2) U' r","y2 r U' r2 U r2 U r2 U' r","l U' l2 U l2 U l2 U' l","R B' R2 F R2 B R2 F' R","y2 R' F R' F' R2 U2 B' R B R'","y F R' F2 R U2 R U2 R' F","y F U R U' R' F' R' U' R U' R' U2 R","y2 F R U R' U' F2 U' L' U L F","y L' U2 L U L' U L F' L' U' L U F","U F R' F2 R U2 R U2 R' F","y2 r U2 R2 U' R2 U' R2 U2 R U2 M","U2 r U' r2 U r2 U r2 U' r","y2 S R U2 R2 U' R2 U' R2 U2 R U S'","R f' U2 F U2 f R2 F' R","y' R' U2 R U R' U R F R U R' U' F'","y F' L' U L U L' U' L U' L' U L F","R U R' U' R' F R F' U F R' F' R U R U' R'","y F L' U2 L U2 L F2 L' F","y2 r U R' U R U2 r' l' U2 L U L' U l","y r' U' R U' R' U2 r2 U2 R' U' R U' r'","y F U R U' R' F' U R U2 R' U' R U' R'","y2 r U2 R2 U' R2 U' r2 U2 R U2 M'","y2 L F' L2 B L2 F L2 B' L","y2 R' F R' F' R2 d2 y' R' F R F'","y' F' L F' L' F2 U2 R' F R F'","y2 r U2 R2 U' R2 U' r' R' U2 R"]],
    [50,"L Shapes","r U' r2' U r2' U r2' U' r",["r' U (r2 U') (r2 U') (r2) U r'","r' U r2 U' r2 U' r2 U r'","y2 R' F R2 B' R2 F' R2 B R'","y' R U2 R' U' R U' R' F R U R' U' F'","y2 l' U l2 U' l2 U' l2 U l'","R U R2 F R F' U F R' F' R","y2 F' L' U' L U F2 U R U' R' F'","y' F R U' R' U' R U R' U R U' R' F'","l U' R U R' l' U2 F R' F' R","y' F' L F2 L' U2 L' U2 L F'","r' U r U r' U' r B U' B' S' L' U' L U' L' U2 L U2 S R U R' U' M' U R U' r'","L' U' L U r U' r' F U2 F R' F' R U R U' R'","L' B L2 F' L2 B' L2 F L'","y2 L F' L F L2 U2 B L' B' L","U R' U2 R U R' U R f R U R' U' f'","y' F' U' L' U L F L U L' U L U2 L'","U' R U2 R' U' R U' R' F R U R' U' F'","L' f U2 F' U2 f' L2 F L'","y2 l' U' L U' L' U2 l r U2 R' U' R U' r'","y r U R' U R U2 r2 U2 R U R' U r","y2 l' U2 L2 U L2 U l L U2 L'","y' F' R U2 R' U2 R' F2 R F'","y2 L F' L F L2 d2 y L F' L' F","R B' R B R2 U2 F R' F' R","y F R' F R F2 U2 L F' L' F","L U' y' R' U2 R' U R U' R U2 R d' L'","y2 R' U R U' R2 F R2 U R' U' F' R"]],
    [51,"Line Shapes","f U R U' R' U R U' R' f'",["f (R U R' U') (R U R' U') f'","y2 F U R U' R' U R U' R' F'","f R U R' U' R U R' U' f'","y' R' U' R' F R F' R U' R' U2 R","y r' F' U' F U F' U' F U r","y2 F R U R' U' R U R' U' R U R' U' R U R' U' F'","U' R' U' R' F R F' R U' R' U2 R","y' R' U' F' U F U' F' U F R","R U2 R' U2 R' F R2 U R' U' F'","y' R U R' U' R U R' U' R' F R2 U' R' U' R U R' F' R U R' U R' F R F'","y' L U L F' L' F L' U L U2 L'","U2 F U R U' R' U R U' R' F'","U2 F U R U' R' U R U' R' F'","y R' U2 R U R' F R' F' R U R","F' U' L' U L U' L' U L F","y2 f' L' U' L U L' U' L U f"]],
    [52,"Line Shapes","F R U R' d R' U' R U' R'",["y2 R' (F' U' F U') (R U R' U) R","y2 R' F' U' F U' R U R' U R","R U R' U R U' B U' B' R'","R U R' U R d' R U' R' F'","R U R' U R U' y R U' R' F'","R' U' R U' R' U y' R' U R B","R' U' R U' R' U F' U F R","y2 R' U' F R' F' R F R' F' R U R","R U R' U R U' f R' f' R'","y F R U R' U' F' U2 R U R' U R U2 R'","y2 R f R f' U R' U' R U' R'","y' F U R U' R' F' r U R' U R U2 r'","y' F U R U' R2 F' R U2 R U2 R'","R U R' U R U2 R' U F U R U' R' F'","R U R' U R U' x' U F' U' R' x","U F U R U2 R' U2 R U2 R' U' F'","R' U' R U' R' U2 R U' f' L' U' L U f","y' R' F R F' U2 R U R' U' R' F R F' R U' R'","y r U2 R' U' R U' r' F R U R' U' F'","R U R' U R U2 R' U' f R U R' U' f'","y2 R U2 R2 u' R U' R' U R' u R","U r U2 R' U' R U' r' F R U R' U' F'","L F U F' U L' U' L U' L'","y f U R U' R' f' R' U' R U' R' U2 R","y2 R U x' U' R U R' U' R U l' U' R'","y2 R U R' U F R U' R' U F' L' U L R U2 R'","y' F R U R' U' F' U' R U2 R' U' R U' R'","R U R' U' M' U R U' r' U' r U r' U2 r U2 R' U2 R U' r'","y2 L U L' U L U' F U' F' L'","y R U' R' F' U' F U2 R U R' U' R U R'","U' F R' F' r U M U R U' R' U R U' M' U' r'","y' F R U R' y' U R' U' R U' R'","y F R U R' U' F' L U L' U L U2 L'","y2 L U L' U L U' y' z' U L' U' b'","R U R' U R y U' R U' R' F'","x' R F R' F R F' U F' U' R' x","U2 R' F' U' F U' R U R' U R","y' F U l' U R U' R' U l F' U' F'","R' U' F' U F' L F L' F R","R' U' y L' U L' y' L F L' F R","y2 L' U' L U' L' U B' U B L","r' U' R' F R F' R' F R F' U r","R' U' R U' R' d R' U R B","y F U R U2 R' U2 R U2 R' U' F'","y2 R U2 R2 U' R U' R' U2 r U R U' r'"]],
    [53,"L Shapes","r' U2' R U R' U' R U R' U r",["(r' U' R U') (R' U R U') (R' U2 r)","r' U' R U' R' U R U' R' U2 r","y2 l' U' L U' L' U L U' L' U2 l","y r' U2 R U R' U' R U R' U r","y' l' U2 L U L' U' L U L' U l","y2 F R U R' U' F' R U R' U' R' F R F'","y2 R' F' r U' r' F r U' r' F2 R","f R U R' U' f' L F R' F' L' F R F'","y' l' U' l L' U' L U L' U' L U l' U l","y' R' F2 r U r' F' r U r' F R","f R U R' U' f' r U R' U' L' U l F'","x' D' L2 U L U' L' U L U' L D x","U r' U2 R U R' U' R U R' U r","U2 l' U' L U' L' U L U' L' U2 l","y r U' r' U' r U r' U r U R' U' M","U2 F R U R' U' F' R U R' U' R' F R F'","y' R' F R F' U' F R' F' R2 U' R'","y' R' F R F' U2 R2 B' R' B R'","F' L F L' U2 F2 R' F' R F'","y' R' F R F' U2 R2 y R' F' R F'","y r' U' r R' U' R U R' U' R U r' U r","y' R' F R F' U2 l R U' R' U l'","y2 F R U R' U' R U' R' U R U R' F'","f R U R' U' f' r U R' U' r' F R F'","R U2 R' U' R U' R' U R U R' U R U' R' U' R' F R F'","y2 R' F' r U' L' U L U' r' F2 R"]],
    [54,"L Shapes","r U2' R' U' R U R' U' R U' r'",["(r U R' U) (R U' R' U) (R U2 r')","r U R' U R U' R' U R U2 r'","y' r U2 R' U' R U R' U' R U' r'","y' r U r' R U R' U' R U R' U' r U' r'","y2 l U L' U L U' L' U L U2 l'","y' x U' L U2 R' U' M U' L' U L U R U R' U' R U' R'","y l U2 L' U' L U L' U' L U' l'","F' L' U' L U F U2 R U R' U' R' F R F'","F' L' U' L U F L' U' L U L F' L' F","y l U l' L U L' U' L U L' U' l U' l'","y' F R U R' U' S R U R' U' R U R' U' f'","R U' R' F R' F' R F R' F' R U' R U R' U2 R U' R'","y2 f' L' U' L U f U2 L F R' F' L' F R F'","y2 M R U R' U R U' R' U R U2 R' U' M'","y r' U2 R U R' U r R' U2 R U R' U R","y f R U R' U' f' R U2 R2 U' R2 U' R2 U2 R","U' r U2 R' U' R U R' U' R U' r'","y' F U R U' R' U R U' R' S U R U' R' f'","y R B' R' B U2 R2 F R F' R","y2 F R' F' R U2 F2 L F L' F","y' L F' L' F U2 L2 y' L F L' F","y' r U' r' F U2 r2 F r U' r","F' L' U' L U L' U L U' L' U' L F"]],
    [55,"Line Shapes","F R' F' U2' R U R' U R2' U2' R'",["R U2 R2 (U' R U' R') U2 (F R F')","y R' F U R U' R2 F' R2 U R' U' R","y R' F R U R U' R2 F' R2 U' R' U R U R'","R U2 R2 U' R U' R' U2 F R F'","r U2 R2 F R F' U2 r' F R F'","y F U' R2 D R' U2 R D' R2 U F'","y F R U R' U' S R U R' U' S' R U R' U' F'","y' r U2 R' U' r' R2 U R' U' r U' r'","y F' U r2 U' r F2 r' U r2 U' F","R' U F2 D' F U2 F' D F2 U' R","R' U' F R' F' R F U R U' R' F' R","y' F R U R' U' F' R U2 R2 U' R2 U' R2 U2 R","y r U2 R' U' M R U R' U' r U' r'","y F R U R' U' F' R U2 R2 U' R2 U' R2 U2 R","R' U' F U R U' R B' R2 F' R2 B R'","L' U2 L2 U L' U L U2 F' L' F","L U2 L2 U' L U' L' U2 f U f'","R' U2 R U R' U R U' F R U' R' U' R U R' F'","R' U' R' F R F' U F' r U R U' r' F","M' U R U' r' F R' F' R U R U R' U' R' F R F'","R U R' S' R U' R' S R U R' U R U' R' U R U2 R'","R U R' U F R' F' R2 U' R' U' R' F' R U2 R U2 R' F","R U2 R2 U' R U' R' U2 y L F L'","y R U R' U2 R U' R' U R' F R F' R' F R F' R U R'","R' U2 R2 U R' U R U2 f' U' f","y' R' F R U R U' R2 F' R2 U' R' U R U R'","R' d R2 D' R U2 R' D R2 U' B","y R U' r' U' R U' R' U r U R' U' M U M'","y R U2 R' U' R U' R' U' r' U' R U' R' U2 r","U r U2 R' U' r' R2 U R' U' r U' r'","y r U' r' U' r U r' R U R' r U' r' U r U r'","U R' F U R U' R2 F' R2 U R' U' R","U R' F R U R U' R2 F' R2 U' R' U R U R'","U' R' F U R U' R2 F' R2 U R' U' R","y R U R' U R U' R' F' R U R' U' R' F R U' R' F R F'","R U' y R2 D R' U2 R D' R2 U F'","y r U2 R' U' r' R2 U R' U' r U' r'","y B' U x R2 F' R B2 R' F R2 x' U' B","R U' y R2 D R' U2 R D' R2 d R'","R' U2 R2 U R' U R U2 y R' F' R","y M U2 r U' r' U' r U' r' U r U R'","y r U2 R' U' R2 r' U R' U' r U' r'","y F R' F' R U R U' R2 F2 r U r' F R"]],
    [56,"Line Shapes","r U r' R U R' U' R U R' U' r U' r'",["(r U r') (U R U' R') (U R U' R') (r U' r')","r U r' U R U' R' U R U' R' r U' r'","r U r' U R U' R' M' U R U2 r'","F R U R' U' R F' r U R' U' r'","r' U' r U' R' U R U' R' U R r' U r","f R U R' U' F' R U R' U' R' F R f'","r U r' U R U' R' U R U' M' U' r'","R' F' R U' r' F r M' U' r' F2 R","F R U R' U' F' r U R' U' r' F R F'","R B L B' R2 f R U' R' f' R","R U R' U' R' F R U R U' R' U R U' R2 F' R U R U' R'","R' F' R U' L' U L U' L' U L R' F R","y R U' R' M' U' R U' R' U r' R2 U R'","y F R U R' U' R U R' U' S R U R' U' f'","y f R U R' U' f' F R U R' U' R U R' U' F'","R' F' R U' r' F r2 R' U' r' F2 R","r U R U' r2 D F R' F' D' r","R' F' r' D R2 D' F' r U F R'","l' U' l U' L' U L U' L' U L l' U l","y R S U' R' U' R U' R' U R U S' R'","r U R' U R U r' U' r U r' F' U F","R' F' R U' L' U L M' U' L' U2 l","r' U' r U' R' U R U' R' U M U r","r U r' U R U' R' U R U' R' L F' L'","R U R' U R U' R' S U R U' R' S' R U' R'","R U R' S U R U' R' U R U' R' S' R U' R'","y R U R' U R' U' F' U F R U R U2 R'","L F L' U R U' R' U R U' R' L F' L'","F R U R' U' F' L F R' F' L' F R F'","R' F' R U' r' F r U' r' F M' F R","y f R U R' U' S' R U R' U' R U R' U' F'","U R U R' U R' U' F' U F R U R U2 R'","l' U' l U' L' U L M' U' L' U2 l","L' B' L U' R' U R U' R' U R L' B L","L' U2 R U' r B R' U2 R' U' R U' x'","y R U' R' U' S' R U' R' S U R U R'"]],
    [57,"All Corners Oriented","r U R' U' M U R U' R'",["(R U R' U') M' (U R U' r')","R U R' U' M' U R U' r'","y R U' R' S' R U R' S","y R U R' S' R U' R' S","R U R' U' R' r U R U' r'","y S R' F R S' R' F' R","R U R' U' r R' U R U' r'","M' U' M U M' U' M U' M' U2 M","r' F' r U M' U' r' F R","L' R U R' U' L R' F R F'","L' U' L U M' U' L' U l","M' U' M' U' M' U2 M U' M U' M","R U R' U' R' L F R F' r'","y M' U M' U M' U M2 U M' U M' U M'","l F l' U' M' U R U' r'","y F' r' U' r F r2 D' r U r' D r2","R L' U R' U' L R' F R F'","M' U M' U M' U2 M U M U M","M' U M U M' U M U M' U2 M U M' U M U M' U M","y S R' F R F' S' F R' F' R","M' U' M U M' U' M U' M U2 M' U' M2 U' M2","M' U M' U M' U M' U' M' U' M' U' M' U' M'","y M' U' M U' M' U' M U M' U M","y R U R' U' M U R U' R' U' M'","F R U' R' U R U R2 F' r U R U' r'","M' U M U' M' U M U M' U2 M","R' U' R U M U' R' U r","L' U' L U l' L U' L' U l","y M' U' M' U' M' U' M2 U' M' U' M' U' M'","M' U' M' U' M' U' M' U' M U M U M U M","M' U' M' U' M' U' M' U2 M' U' M' U' M' U' M'","R U' R' F' U F R U R2 F R F'","R U R' S R U' R' U S'","y M' U M' U M' U M' U M' U' M' U' M' U' M'","M F R' F' M' F R F'"]]
];

const FACE_NAMES = Object.freeze(['U', 'R', 'F', 'D', 'L', 'B']);
const FACE_NAME_SET = new Set(FACE_NAMES);
const MAX_OLL_BASE_SCRAMBLE_MOVES = 20;
const SIDE_FACE_CYCLE = Object.freeze(['R', 'B', 'L', 'F']);
const IDENTITY_FACE_MAP = Object.freeze({ U: 'U', R: 'R', F: 'F', D: 'D', L: 'L', B: 'B' });
const ROTATION_FACE_MAPS = Object.freeze({
    x: Object.freeze({ U: 'F', R: 'R', F: 'D', D: 'B', L: 'L', B: 'U' }),
    "x'": Object.freeze({ U: 'B', R: 'R', F: 'U', D: 'F', L: 'L', B: 'D' }),
    x2: Object.freeze({ U: 'D', R: 'R', F: 'B', D: 'U', L: 'L', B: 'F' }),
    y: Object.freeze({ U: 'U', R: 'B', F: 'R', D: 'D', L: 'F', B: 'L' }),
    "y'": Object.freeze({ U: 'U', R: 'F', F: 'L', D: 'D', L: 'B', B: 'R' }),
    y2: Object.freeze({ U: 'U', R: 'L', F: 'B', D: 'D', L: 'R', B: 'F' }),
    z: Object.freeze({ U: 'L', R: 'U', F: 'F', D: 'R', L: 'D', B: 'B' }),
    "z'": Object.freeze({ U: 'R', R: 'D', F: 'F', D: 'L', L: 'U', B: 'B' }),
    z2: Object.freeze({ U: 'D', R: 'L', F: 'F', D: 'U', L: 'R', B: 'B' }),
});

// Wide and slice moves expressed as a rotation plus outer-layer turns.
// All components share an axis, so modifiers can be distributed safely.
const MOVE_EXPANSIONS = Object.freeze({
    r: Object.freeze(['x', 'L']),
    Rw: Object.freeze(['x', 'L']),
    l: Object.freeze(["x'", 'R']),
    Lw: Object.freeze(["x'", 'R']),
    u: Object.freeze(['y', 'D']),
    Uw: Object.freeze(['y', 'D']),
    d: Object.freeze(["y'", 'U']),
    Dw: Object.freeze(["y'", 'U']),
    f: Object.freeze(['z', 'B']),
    Fw: Object.freeze(['z', 'B']),
    b: Object.freeze(["z'", 'F']),
    Bw: Object.freeze(["z'", 'F']),
    M: Object.freeze(["x'", 'R', "L'"]),
    E: Object.freeze(["y'", 'U', "D'"]),
    S: Object.freeze(['z', "F'", 'B']),
});

function normalizeWhitespace(value) {
    return String(value ?? '')
        .replace(/[´‘’′]/g, "'")
        .replace(/[()[\]{},]/g, ' ')
        .replace(/\s+/g, ' ')
        .trim();
}

function modifierToPower(modifier = '') {
    if (modifier === "'" || modifier === '3') return 3;
    if (modifier === '2' || modifier === "2'") return 2;
    if (modifier === "3'") return 1;
    return 1;
}

function powerToModifier(power) {
    const normalizedPower = ((power % 4) + 4) % 4;
    if (normalizedPower === 0) return null;
    if (normalizedPower === 1) return '';
    if (normalizedPower === 2) return '2';
    return "'";
}

function splitMoveToken(token) {
    const match = String(token ?? '').match(/^([URFDLBMESxyzurfdlb](?:w)?)(2'?|3'?|'|)?$/);
    if (!match) return null;
    return { base: match[1], power: modifierToPower(match[2] || '') };
}

function applyPower(token, outerPower) {
    const parsed = splitMoveToken(token);
    if (!parsed) return null;
    const modifier = powerToModifier(parsed.power * outerPower);
    return modifier == null ? null : parsed.base + modifier;
}

function composeFaceMaps(outerMap, innerMap) {
    return Object.fromEntries(FACE_NAMES.map((face) => [face, outerMap[innerMap[face]]]));
}

function simplifyFaceTurns(tokens) {
    const simplified = [];

    tokens.forEach((token) => {
        const parsed = splitMoveToken(token);
        if (!parsed || !FACE_NAME_SET.has(parsed.base)) return;

        const previous = simplified[simplified.length - 1];
        const previousParsed = splitMoveToken(previous);
        if (!previousParsed || previousParsed.base !== parsed.base) {
            simplified.push(parsed.base + (powerToModifier(parsed.power) || ''));
            return;
        }

        simplified.pop();
        const modifier = powerToModifier(previousParsed.power + parsed.power);
        if (modifier != null) simplified.push(parsed.base + modifier);
    });

    return simplified;
}

export function normalizeAlgorithmToFaceTurns(algorithm) {
    const normalized = normalizeWhitespace(algorithm);
    if (!normalized) return '';

    const expanded = [];
    for (const token of normalized.split(' ')) {
        const parsed = splitMoveToken(token);
        if (!parsed) return '';

        const expansion = MOVE_EXPANSIONS[parsed.base] || [parsed.base];
        for (const component of expansion) {
            const poweredComponent = applyPower(component, parsed.power);
            if (poweredComponent) expanded.push(poweredComponent);
        }
    }

    const output = [];
    let orientationMap = IDENTITY_FACE_MAP;

    for (const token of expanded) {
        const parsed = splitMoveToken(token);
        if (!parsed) return '';

        if (FACE_NAME_SET.has(parsed.base)) {
            output.push(orientationMap[parsed.base] + (powerToModifier(parsed.power) || ''));
            continue;
        }

        if (!['x', 'y', 'z'].includes(parsed.base)) return '';
        const rotationModifier = powerToModifier(parsed.power) || '';
        const rotationMap = ROTATION_FACE_MAPS[parsed.base + rotationModifier];
        if (!rotationMap) return '';
        orientationMap = composeFaceMaps(orientationMap, rotationMap);
    }

    return simplifyFaceTurns(output).join(' ');
}

export function invertFaceTurnAlgorithm(algorithm) {
    const normalized = normalizeAlgorithmToFaceTurns(algorithm);
    if (!normalized) return '';

    const solutionMoves = normalized.split(' ');
    // AUF is redundant for a trainer case, but it must be removed only after
    // rotations and wide moves have been resolved into the fixed cube frame.
    // A literal trailing U in the source may normalize to another face, while
    // a different source-face move may normalize to U.
    while (solutionMoves.length > 0 && splitMoveToken(solutionMoves[solutionMoves.length - 1])?.base === 'U') {
        solutionMoves.pop();
    }

    return solutionMoves
        .reverse()
        .map((token) => {
            const parsed = splitMoveToken(token);
            return parsed.base + (powerToModifier(4 - parsed.power) || '');
        })
        .join(' ');
}

function moveCount(algorithm) {
    return String(algorithm ?? '').split(' ').filter(Boolean).length;
}

export function canonicalizeLastLayerScramble(scramble) {
    const moves = scramble.split(' ').filter(Boolean);
    // The generator adds a uniformly random final AUF, so an existing final U
    // move does not distinguish the set or distribution of generated scrambles.
    if (/^U(?:2|')?$/.test(moves[moves.length - 1] || '')) moves.pop();

    const rotations = Array.from({ length: 4 }, (_, rotationIndex) => moves
        .map((move) => {
            const faceIndex = SIDE_FACE_CYCLE.indexOf(move[0]);
            if (faceIndex < 0) return move;
            return SIDE_FACE_CYCLE[(faceIndex + rotationIndex) % SIDE_FACE_CYCLE.length] + move.slice(1);
        })
        .join(' '));

    return rotations.sort()[0];
}

function selectUniqueOllAlgorithms(algorithms) {
    const seenScrambles = new Set();

    return algorithms.filter((algorithm) => {
        const scramble = invertFaceTurnAlgorithm(algorithm);
        if (!scramble || moveCount(scramble) > MAX_OLL_BASE_SCRAMBLE_MOVES) return false;

        const scrambleKey = canonicalizeLastLayerScramble(scramble);
        if (seenScrambles.has(scrambleKey)) return false;
        seenScrambles.add(scrambleKey);
        return true;
    });
}

function remapFaceTurns(algorithm, rotationIndex) {
    const normalized = normalizeAlgorithmToFaceTurns(algorithm);
    if (!normalized || rotationIndex % 4 === 0) return normalized;

    const rotationToken = ['', 'y', 'y2', "y'"][rotationIndex % 4];
    const faceMap = ROTATION_FACE_MAPS[rotationToken];

    return normalized
        .split(' ')
        .map((token) => {
            const parsed = splitMoveToken(token);
            return faceMap[parsed.base] + (powerToModifier(parsed.power) || '');
        })
        .join(' ');
}

function randomIndex(length, random = Math.random) {
    return Math.floor(random() * length);
}

function randomAuf(random = Math.random) {
    return ['', 'U', 'U2', "U'"][randomIndex(4, random)];
}

export function createLastLayerCaseScramble(trainerCase, random = Math.random) {
    const candidateAlgorithms = trainerCase?.scrambleAlgorithms || trainerCase?.algorithms;
    if (!trainerCase || !Array.isArray(candidateAlgorithms) || candidateAlgorithms.length === 0) {
        throw new Error('Cannot generate a last-layer scramble without case algorithms.');
    }

    // Treat an eligible spreadsheet setup as one candidate alongside every
    // inverted solution, rather than making it the fixed scramble for this case.
    const includeSetup = trainerCase.includeSetupInScrambles !== false;
    const candidateIndex = randomIndex(candidateAlgorithms.length + (includeSetup ? 1 : 0), random);
    const baseSetup = includeSetup && candidateIndex === 0
        ? trainerCase.setup
        : invertFaceTurnAlgorithm(candidateAlgorithms[candidateIndex - (includeSetup ? 1 : 0)]);
    if (!baseSetup) {
        throw new Error('Failed to select a valid last-layer scramble for case ' + trainerCase.name + '.');
    }

    const remappedSetup = remapFaceTurns(baseSetup, randomIndex(4, random));
    const scramble = simplifyFaceTurns([
        ...remappedSetup.split(' ').filter(Boolean),
        randomAuf(random),
    ].filter(Boolean)).join(' ');

    if (!scramble || !scramble.split(' ').every((token) => /^[UDRLFB](?:2|')?$/.test(token))) {
        throw new Error('Failed to normalize last-layer scramble for case ' + trainerCase.name + '.');
    }

    return scramble;
}

function createOllCase(number, category, setup, algorithms) {
    const normalizedSetup = normalizeAlgorithmToFaceTurns(setup);
    let scrambleSelection = null;

    const getScrambleSelection = () => {
        if (scrambleSelection) return scrambleSelection;

        const scrambleAlgorithms = Object.freeze(selectUniqueOllAlgorithms(algorithms));
        const algorithmScrambleKeys = new Set(scrambleAlgorithms
            .map((algorithm) => canonicalizeLastLayerScramble(invertFaceTurnAlgorithm(algorithm))));
        const includeSetupInScrambles = Boolean(normalizedSetup)
            && moveCount(normalizedSetup) <= MAX_OLL_BASE_SCRAMBLE_MOVES
            && !algorithmScrambleKeys.has(canonicalizeLastLayerScramble(normalizedSetup));

        scrambleSelection = Object.freeze({ scrambleAlgorithms, includeSetupInScrambles });
        return scrambleSelection;
    };

    return Object.freeze({
        id: String(number),
        number,
        name: 'OLL ' + number,
        category,
        setup: normalizedSetup,
        algorithms: Object.freeze([...algorithms]),
        get includeSetupInScrambles() {
            return getScrambleSelection().includeSetupInScrambles;
        },
        get scrambleAlgorithms() {
            return getScrambleSelection().scrambleAlgorithms;
        },
    });
}

export const OLL_CASES = Object.freeze(RAW_OLL_CASES.map((ollCase) => createOllCase(...ollCase)));

export const OLL_CASE_IDS = Object.freeze(OLL_CASES.map(({ id }) => id));
const OLL_CASE_ID_SET = new Set(OLL_CASE_IDS);

export function sanitizeOllCaseSelection(value) {
    if (!Array.isArray(value)) return [...OLL_CASE_IDS];

    const selected = [...new Set(value
        .map((id) => String(id ?? '').trim())
        .filter((id) => OLL_CASE_ID_SET.has(id)))];

    return selected.length > 0 ? selected : [...OLL_CASE_IDS];
}

export function getOllCase(caseId) {
    const normalizedId = String(caseId ?? '').trim();
    return OLL_CASES.find(({ id }) => id === normalizedId) ?? null;
}

export function createOllCaseScramble(allowedCaseIds = OLL_CASE_IDS, random = Math.random) {
    const selectedIds = sanitizeOllCaseSelection(allowedCaseIds);
    const caseId = selectedIds[randomIndex(selectedIds.length, random)];
    const ollCase = getOllCase(caseId) || OLL_CASES[0];

    return {
        text: createLastLayerCaseScramble(ollCase, random),
        caseId: ollCase.id,
    };
}
