name = "ukratimer-battle"
main = "worker.js"
compatibility_date = "2026-04-27"

[durable_objects]
bindings = [
  { name = "BATTLE_ROOM", class_name = "BattleRoom" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["BattleRoom"]
